! Prototype for managing model fields in the IFS
!
! Much has been copied from (or inspired by) the new GOMs  - obviously
! the GOMs would eventually use the field module stuff, not duplicate it!
!
! This code is far from perfect yet and there is some scope for performance
! tuning, but that can wait until profiling tells us what is actually slow.
!
! AJG 24/10/2012
! F Suzat 07/06/2021 Memory leak correction
MODULE FIELD_CONTAINER_GP_MOD

USE PARKIND1              , ONLY : JPIM, JPRB
USE YOMHOOK               , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMGFL                , ONLY : TGFL
USE YOMGMV                , ONLY : TGMV
USE SURFACE_FIELDS_MIX    , ONLY : TSURF
USE FIELD_DEFINITIONS_BASE, ONLY : TYPE_FVAR,TYPE_CONTROL,JP_T0_DL,JP_T0_DM,JP_T9_DL,JP_T9_DM,JP_T0,JP_T9,&
 &                                 FIELD_ACCESS_BASE, FIELD_METADATA_BASE
USE FIELD_DEFINITIONS     , ONLY : FIELD_ACCESS
USE FIELD_GFL_WRAPPER     , ONLY : GFL_MAPPING_SETUP, GFL_FID_SETUP, GFL_ATTACH, GFL_AS_A_WHOLE,GFL_MAP
USE FIELD_CONTAINER_BASE_MOD

IMPLICIT NONE

PRIVATE

! -------------------------------------------------
! Public interface
! -------------------------------------------------


! -------------------------------------------------


INTEGER(KIND=JPIM), PARAMETER :: JP_ALL_BLOCKS = 0

! Storage scheme: NFTBC eventually, delete all but the best one.
!INTEGER(KIND=JPIM), PARAMETER :: JP_STORAGE1D  = 1 ! basic 1d storage scheme (not rank-conformant at f95)
INTEGER(KIND=JPIM), PARAMETER :: JP_STORAGE3D  = 4 ! "3d" storage scheme preserving rank-conformance
!INTEGER(KIND=JPIM), PARAMETER :: JP_STORAGEOLD = 3 ! backward compatibility: use old gfl, gmvs etc.

INTEGER(KIND=JPIM), PARAMETER :: JP_FADD=1,JP_FCOPY=2
! 5) Derived types, constants
PUBLIC :: FIELD_CONTAINER_GP

TYPE,EXTENDS(TYPE_FIELD_INDEX_BASE) ::  TYPE_FIELD_INDEX

  ! For one variable
  INTEGER(KIND=JPIM) :: ISTART=-1
  INTEGER(KIND=JPIM) :: IEND=-1
  LOGICAL :: L_HDERS = .FALSE.
  TYPE(TYPE_FIELD_INDEX),POINTER :: DM !=> NULL()
  TYPE(TYPE_FIELD_INDEX),POINTER :: DL => NULL()

END TYPE TYPE_FIELD_INDEX

TYPE,EXTENDS(FIELD_CONTAINER_BASE) :: FIELD_CONTAINER_GP
  PRIVATE

  ! Storage type (e.g. 1D, 3D, attach to old GFLS etc.)
  TYPE(TGMV),POINTER         :: YRGMV=>NULL()
  TYPE(TGFL),POINTER         :: YRGFL=>NULL()
  TYPE(TSURF),POINTER        :: YRSURF=>NULL()

  ! 1D Storage area and its size; indexes into the storage area
  INTEGER(KIND=JPIM)             :: ILEN_STORAGE1D
  REAL(KIND=JPRB), ALLOCATABLE   :: STORAGE1D(:)
  TYPE(TYPE_FIELD_INDEX),ALLOCATABLE :: INDEX_GP(:)
  TYPE(TYPE_FIELD_INDEX),ALLOCATABLE :: INDEX_BLOCK(:,:)

  ! GFL-mapping storage area NFTBC
  LOGICAL :: L_ATTACH_GFL_NPROMA_FIXED  ! TRUE = turns OFF the last block hack
  REAL(KIND=JPRB), ALLOCATABLE :: STORAGE_LAST_BLOCK(:,:,:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: INDEX_LAST_BLOCK(:)
  REAL(KIND=JPRB), ALLOCATABLE    :: UNASSIGNED_GFL(:,:,:) ! to deal with unused fields

  ! Properties of all fields that have been defined
  INTEGER(KIND=JPIM)          :: NHDERS=0

  ! Basic dimensions
  INTEGER(KIND=JPIM)          :: NBLOCKS
  INTEGER(KIND=JPIM), ALLOCATABLE :: NPOINTS_BLOCK(:) ! "nproma" kind of thing

  ! List of all the fields that actually in use
  LOGICAL                     :: LHDERS

  CONTAINS
! 1) Creator and destructor
  PROCEDURE ::  FIELD_CREATE
  PROCEDURE ::  FIELD_DESTROY
! 2) Direct field access
  PROCEDURE :: FIELD_OPEN_FAC
  PROCEDURE :: FIELD_CLOSE_FAC
  PROCEDURE :: FIELD_OPEN_ONE_1D
  PROCEDURE :: FIELD_OPEN_ONE_2D
  PROCEDURE :: FIELD_OPEN_ONE_3D
  GENERIC   :: FIELD_OPEN_ONE => FIELD_OPEN_ONE_1D
  GENERIC   :: FIELD_OPEN_ONE => FIELD_OPEN_ONE_2D
  GENERIC   :: FIELD_OPEN_ONE => FIELD_OPEN_ONE_3D
  PROCEDURE :: FIELD_CLOSE_ONE_1D
  PROCEDURE :: FIELD_CLOSE_ONE_2D
  PROCEDURE :: FIELD_CLOSE_ONE_3D
  GENERIC   :: FIELD_CLOSE_ONE => FIELD_CLOSE_ONE_1D
  GENERIC   :: FIELD_CLOSE_ONE => FIELD_CLOSE_ONE_2D
  GENERIC   :: FIELD_CLOSE_ONE => FIELD_CLOSE_ONE_3D
  PROCEDURE :: FIELD_OPEN_MULTI
  PROCEDURE :: FIELD_CLOSE_MULTI
  PROCEDURE :: FIELD_ITERATED
! 3) Field operators (indirect access)
  PROCEDURE :: FIELD_EQUALS
  PROCEDURE :: FIELD_ADD
  PROCEDURE :: FIELD_COPY
  PROCEDURE :: FIELD_NORM
! 4) Multi-threading helpers; inquiry functions
  PROCEDURE :: FIELD_BLOCK_SIZE
  PROCEDURE :: FIELD_NBLOCKS
!  PROCEDURE :: FIELD_ACTIVE_CONTAINER
  PROCEDURE :: KINDEX_OLD
END TYPE FIELD_CONTAINER_GP


CONTAINS

SUBROUTINE FIELD_CREATE(SELF,NAMESPACE,KPOINTS,KLEVELS,KPROMA,KFIDS,KFSET,KATTACH,YDGMV,YDGFL,YDSURF,&
  & LD_ATTACH_GFL_NPROMA_FIXED,LDHDERS,KDIM3S)





CLASS(FIELD_CONTAINER_GP) ,   INTENT(INOUT) :: SELF
CLASS(FIELD_METADATA_BASE),   INTENT(IN)    :: NAMESPACE  
INTEGER(KIND=JPIM),           INTENT(IN)    :: KPOINTS    
INTEGER(KIND=JPIM),           INTENT(IN)    :: KLEVELS(:) 
INTEGER(KIND=JPIM),           INTENT(IN)    :: KPROMA     
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: KFIDS(:)    
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: KFSET       
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: KATTACH     

TYPE(TGMV),OPTIONAL,TARGET ,INTENT(IN)      :: YDGMV
TYPE(TGFL) ,OPTIONAL,TARGET  ,INTENT(IN)    :: YDGFL
TYPE(TSURF) ,OPTIONAL,TARGET  ,INTENT(IN)   :: YDSURF

LOGICAL           , OPTIONAL, INTENT(IN)    :: LD_ATTACH_GFL_NPROMA_FIXED 
LOGICAL           , OPTIONAL, INTENT(IN)    :: LDHDERS 
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: KDIM3S(:)

INTEGER(KIND=JPIM) :: ID, ISIZE_ALL, ISIZE_VAR, IBLOCK, INLEVELS, I, I2D
INTEGER(KIND=JPIM) :: ISIZE_BLOCK, IMAXLEV
INTEGER(KIND=JPIM) :: IKGLO
LOGICAL,ALLOCATABLE :: LLON(:),LLACTIVE(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE






























END SUBROUTINE FIELD_CREATE
!=======================================================================================
SUBROUTINE FIELD_DESTROY(SELF)



CLASS(FIELD_CONTAINER_GP), INTENT(INOUT) :: SELF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE






END SUBROUTINE FIELD_DESTROY
!=======================================================================================
SUBROUTINE FIELD_OPEN_FAC(SELF, KFIDS, KBLOCK, FAC, KBLOCK_SIZE,KFIDS_HD)






CLASS(FIELD_CONTAINER_GP),           INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM), TARGET, OPTIONAL,INTENT(IN)    :: KFIDS(:)
INTEGER(KIND=JPIM),                  INTENT(IN)    :: KBLOCK
CLASS(FIELD_ACCESS_BASE),            INTENT(OUT)   :: FAC
INTEGER(KIND=JPIM), OPTIONAL,        INTENT(OUT)   :: KBLOCK_SIZE
INTEGER(KIND=JPIM), TARGET, OPTIONAL,INTENT(IN)    :: KFIDS_HD(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE










END SUBROUTINE FIELD_OPEN_FAC
!=======================================================================================
SUBROUTINE FIELD_OPEN_COMMON(SELF, ACCESS_CONTROL, KFIELDS, KFIDS, KBLOCK, KBLOCK_SIZE)

CLASS(FIELD_CONTAINER_GP),            INTENT(INOUT) :: SELF
TYPE(TYPE_CONTROL),                   INTENT(OUT)   :: ACCESS_CONTROL
INTEGER(KIND=JPIM), POINTER          ,INTENT(OUT)   :: KFIELDS(:) 
INTEGER(KIND=JPIM), OPTIONAL, TARGET, INTENT(IN)    :: KFIDS(:) 
INTEGER(KIND=JPIM),                   INTENT(IN)    :: KBLOCK   
INTEGER(KIND=JPIM), OPTIONAL,         INTENT(OUT)   :: KBLOCK_SIZE 

INTEGER(KIND=JPIM) :: IFIELDS_USED, ID, IUSED_FIDS(SELF%NFIELDS),J
LOGICAL :: LLON,LLHDERS























END SUBROUTINE FIELD_OPEN_COMMON

!=======================================================================================
SUBROUTINE FIELD_CLOSE_FAC(SELF, FAC)





CLASS(FIELD_CONTAINER_GP), INTENT(INOUT) :: SELF
CLASS(FIELD_ACCESS_BASE) , INTENT(INOUT) :: FAC










END SUBROUTINE FIELD_CLOSE_FAC
!=======================================================================================
SUBROUTINE FIELD_OPEN_ONE_1D(SELF, KFID, KBLOCK, PFIELD, KBLOCK_SIZE)





CLASS(FIELD_CONTAINER_GP),  INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),         INTENT(IN)    :: KFID      
INTEGER(KIND=JPIM),         INTENT(IN)    :: KBLOCK   
REAL(KIND=JPRB), POINTER                  :: PFIELD(:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: KBLOCK_SIZE 

INTEGER(KIND=JPIM) :: IFIDS(1)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE









END SUBROUTINE FIELD_OPEN_ONE_1D
!=======================================================================================
SUBROUTINE FIELD_OPEN_ONE_2D(SELF, KFID, KBLOCK, PFIELD, KBLOCK_SIZE)

CLASS(FIELD_CONTAINER_GP),    INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),           INTENT(IN)    :: KFID 
INTEGER(KIND=JPIM),           INTENT(IN)    :: KBLOCK
REAL(KIND=JPRB), POINTER                    :: PFIELD(:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT)   :: KBLOCK_SIZE 

INTEGER(KIND=JPIM) :: IFIDS(1)
REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE








END SUBROUTINE FIELD_OPEN_ONE_2D
!=======================================================================================
SUBROUTINE FIELD_OPEN_ONE_3D(SELF, KFID, KBLOCK, PFIELD, KBLOCK_SIZE)

CLASS(FIELD_CONTAINER_GP),    INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),           INTENT(IN)    :: KFID 
INTEGER(KIND=JPIM),           INTENT(IN)    :: KBLOCK
REAL(KIND=JPRB), POINTER                    :: PFIELD(:,:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT)   :: KBLOCK_SIZE 

INTEGER(KIND=JPIM) :: IFIDS(1)
REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE









END SUBROUTINE FIELD_OPEN_ONE_3D
!=======================================================================================
SUBROUTINE FIELD_CLOSE_ONE_1D(SELF, KFID, KBLOCK, PFIELD)




CLASS(FIELD_CONTAINER_GP),INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),       INTENT(IN)    :: KFID 
INTEGER(KIND=JPIM),       INTENT(IN)    :: KBLOCK   
REAL(KIND=JPRB), POINTER                :: PFIELD(:)

INTEGER(KIND=JPIM) :: IFIDS(1)
REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE







END SUBROUTINE FIELD_CLOSE_ONE_1D
!=======================================================================================
SUBROUTINE FIELD_CLOSE_ONE_2D(SELF, KFID, KBLOCK, PFIELD)

CLASS(FIELD_CONTAINER_GP),INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),       INTENT(IN)    :: KFID 
INTEGER(KIND=JPIM),       INTENT(IN)    :: KBLOCK
REAL(KIND=JPRB), POINTER                :: PFIELD(:,:)

INTEGER(KIND=JPIM) :: IFIDS(1)
REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE









END SUBROUTINE FIELD_CLOSE_ONE_2D
!=======================================================================================
SUBROUTINE FIELD_CLOSE_ONE_3D(SELF, KFID, KBLOCK, PFIELD)

CLASS(FIELD_CONTAINER_GP),INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),       INTENT(IN)    :: KFID 
INTEGER(KIND=JPIM),       INTENT(IN)    :: KBLOCK
REAL(KIND=JPRB), POINTER, INTENT(INOUT) :: PFIELD(:,:,:)

INTEGER(KIND=JPIM) :: IFIDS(1)
REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE









END SUBROUTINE FIELD_CLOSE_ONE_3D
!=======================================================================================
SUBROUTINE FIELD_OPEN_MULTI(SELF, KFIDS, KBLOCK, PFIELD, KBLOCK_SIZE)




CLASS(FIELD_CONTAINER_GP),    INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),           INTENT(IN)    :: KFIDS(:) 
INTEGER(KIND=JPIM),           INTENT(IN)    :: KBLOCK
REAL(KIND=JPRB), POINTER                    :: PFIELD(:,:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT)   :: KBLOCK_SIZE 
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE







END SUBROUTINE FIELD_OPEN_MULTI
!=======================================================================================

SUBROUTINE FIELD_CLOSE_MULTI(SELF, KFIDS, KBLOCK, PFIELD)




CLASS(FIELD_CONTAINER_GP),INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),       INTENT(IN)    :: KFIDS(:) 
INTEGER(KIND=JPIM),       INTENT(IN)    :: KBLOCK
REAL(KIND=JPRB), POINTER                :: PFIELD(:,:,:)

INTEGER(KIND=JPIM) :: ISIZE_GFL, IPOINTS, ILEVELS, IFIELDS
REAL(KIND=JPRB), POINTER :: ZTMP(:,:,:) => NULL()
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE







END SUBROUTINE FIELD_CLOSE_MULTI


FUNCTION FIELD_ITERATED(SELF, KFIDS, KBLOCK, FAC,LDHDERS,KOTID,KBLOCK_SIZE,FVAR)

















INTEGER(KIND=JPIM) :: FIELD_ITERATED

CLASS(FIELD_CONTAINER_GP),TARGET,     INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM), OPTIONAL, TARGET, INTENT(IN)    :: KFIDS(:)      
INTEGER(KIND=JPIM),                   INTENT(IN)    :: KBLOCK        
CLASS(FIELD_ACCESS_BASE),             INTENT(INOUT) :: FAC
LOGICAL,OPTIONAL,                     INTENT(IN)    :: LDHDERS
INTEGER(KIND=JPIM), OPTIONAL,         INTENT(OUT)   :: KOTID         
INTEGER(KIND=JPIM), OPTIONAL,         INTENT(OUT)   :: KBLOCK_SIZE   
TYPE(TYPE_FVAR),POINTER,OPTIONAL,     INTENT(OUT)   :: FVAR
INTEGER(KIND=JPIM)          :: ID, INO_FLDS_ITER
INTEGER(KIND=JPIM), POINTER :: IUSE_FIDS(:)
LOGICAL :: LLHDERS















END FUNCTION FIELD_ITERATED
!=======================================================================================
SUBROUTINE FIELD_EQUALS(SELF, PVALUE, KFIDS, KBLOCK)



CLASS(FIELD_CONTAINER_GP),TARGET,     INTENT(INOUT) :: SELF
REAL(KIND=JPRB),                      INTENT(IN)    :: PVALUE
INTEGER(KIND=JPIM), OPTIONAL, TARGET, INTENT(IN)    :: KFIDS(:)
INTEGER(KIND=JPIM), OPTIONAL,         INTENT(IN)    :: KBLOCK

INTEGER(KIND=JPIM) :: I, ID, ISTART, IEND
INTEGER(KIND=JPIM) :: IUSE_BLOCK, IBLOCK, IBLOCK_START, IBLOCK_END
INTEGER(KIND=JPIM), POINTER :: IUSE_FIDS(:)
REAL(KIND=JPRB), POINTER :: F1D(:), F2D(:,:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE







  



END SUBROUTINE FIELD_EQUALS
!=======================================================================================
SUBROUTINE FIELD_ADD(F1, F2, KFIDS, KBLOCK)




CLASS(FIELD_CONTAINER_GP),                INTENT(INOUT) :: F1
CLASS(FIELD_CONTAINER_GP),                INTENT(INOUT) :: F2
INTEGER(KIND=JPIM), OPTIONAL, TARGET, INTENT(IN)    :: KFIDS(:)
INTEGER(KIND=JPIM), OPTIONAL,         INTENT(IN)    :: KBLOCK
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE





END SUBROUTINE FIELD_ADD
!=======================================================================================

SUBROUTINE FIELD_COPY(F1, F2, KFIDS, KBLOCK)




CLASS(FIELD_CONTAINER_GP),                INTENT(INOUT) :: F1
CLASS(FIELD_CONTAINER_GP),                INTENT(INOUT) :: F2
INTEGER(KIND=JPIM), OPTIONAL, TARGET, INTENT(IN)    :: KFIDS(:)
INTEGER(KIND=JPIM), OPTIONAL,         INTENT(IN)    :: KBLOCK
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE





END SUBROUTINE FIELD_COPY
!=======================================================================================

SUBROUTINE TWO_FIELD_ACTION(F1, F2, KACTION, KFIDS, KBLOCK)














CLASS(FIELD_CONTAINER_GP),TARGET,         INTENT(INOUT) :: F1
CLASS(FIELD_CONTAINER_GP),                INTENT(INOUT) :: F2
INTEGER(KIND=JPIM),                   INTENT(IN)    :: KACTION
INTEGER(KIND=JPIM), OPTIONAL, TARGET, INTENT(IN)    :: KFIDS(:)
INTEGER(KIND=JPIM), OPTIONAL,         INTENT(IN)    :: KBLOCK

INTEGER(KIND=JPIM) :: ID
INTEGER(KIND=JPIM) :: IUSE_BLOCK, IBLOCK, IBLOCK_START, IBLOCK_END
INTEGER(KIND=JPIM), POINTER :: IUSE_FIDS(:)
REAL(KIND=JPRB), POINTER :: F1_1D(:), F1_2D(:,:), F2_1D(:), F2_2D(:,:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE












END SUBROUTINE TWO_FIELD_ACTION
!=======================================================================================
SUBROUTINE FIELD_NORM(SELF)



CLASS(FIELD_CONTAINER_GP), INTENT(INOUT) :: SELF

INTEGER(KIND=JPIM) :: ID, ISIZE, IBLOCK
REAL(KIND=JPRB), POINTER :: ZVAR1D(:), ZVAR2D(:,:), ZVAR3D(:,:,:)
REAL(KIND=JPRB) :: ZRMEAN, ZRRMS, ZRMIN, ZRMAX, ZMEAN, ZRMS, ZMIN, ZMAX
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE






END SUBROUTINE FIELD_NORM
!=======================================================================================
FUNCTION FIELD_NBLOCKS(SELF)



INTEGER(KIND=JPIM)                :: FIELD_NBLOCKS

CLASS(FIELD_CONTAINER_GP), INTENT(IN) :: SELF



END FUNCTION FIELD_NBLOCKS
!=======================================================================================
FUNCTION FIELD_BLOCK_SIZE(SELF,KBLOCK)




INTEGER(KIND=JPIM)                :: FIELD_BLOCK_SIZE
CLASS(FIELD_CONTAINER_GP), INTENT(IN) :: SELF
INTEGER(KIND=JPIM),        INTENT(IN) :: KBLOCK



END FUNCTION FIELD_BLOCK_SIZE
!=======================================================================================

SUBROUTINE MAP_NAMES_TO_STORAGE(SELF, KFIDS, KBLOCK, MFAC, LD_RELEASE,KFIDS_HD)




CLASS(FIELD_CONTAINER_GP),     INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),            INTENT(IN)    :: KFIDS(:), KBLOCK
CLASS(FIELD_ACCESS_BASE), OPTIONAL, INTENT(INOUT) :: MFAC
LOGICAL, OPTIONAL,             INTENT(IN)    :: LD_RELEASE 
INTEGER(KIND=JPIM), TARGET, OPTIONAL,INTENT(IN) :: KFIDS_HD(:)

INTEGER(KIND=JPIM)       :: ID,INFIDS,INHFIDS,IFIDS(SELF%NFIELDS),J
LOGICAL                  :: LL_NULLIFY, LL_RELEASE,LLHDERS,LLHFIDS
REAL(KIND=JPRB), POINTER :: FIELD_1D(:), FIELD_1D_DL(:),FIELD_1D_DM(:)
REAL(KIND=JPRB), POINTER :: FIELD_2D(:,:),FIELD_2D_DL(:,:),FIELD_2D_DM(:,:)
REAL(KIND=JPRB), POINTER :: FIELD_3D(:,:,:),FIELD_3D_DL(:,:,:),FIELD_3D_DM(:,:,:)















END SUBROUTINE MAP_NAMES_TO_STORAGE
!=======================================================================================
SUBROUTINE FMAP_1D(SELF, KBLOCK, KID, FPTR,LDHDERS,FPTR_L,FPTR_M)




CLASS(FIELD_CONTAINER_GP),    INTENT(IN),TARGET  :: SELF
INTEGER(KIND=JPIM),       INTENT(IN)  :: KBLOCK, KID
REAL(KIND=JPRB), POINTER              :: FPTR(:)
LOGICAL,  OPTIONAL,     INTENT(IN)    :: LDHDERS
REAL(KIND=JPRB), OPTIONAL,POINTER     :: FPTR_L(:)
REAL(KIND=JPRB), OPTIONAL,POINTER     :: FPTR_M(:)

INTEGER(KIND=JPIM) :: ISTART, IEND, IPOINTS
LOGICAL :: LL_WANTED,LLHDERS









END SUBROUTINE FMAP_1D
!=======================================================================================

SUBROUTINE FMAP_2D(SELF, KBLOCK, KID, FPTR,LDHDERS,FPTR_L,FPTR_M)




CLASS(FIELD_CONTAINER_GP),TARGET, INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),       INTENT(IN)    :: KBLOCK, KID
REAL(KIND=JPRB), POINTER                :: FPTR(:,:)
LOGICAL,  OPTIONAL,     INTENT(IN)      :: LDHDERS
REAL(KIND=JPRB), OPTIONAL,POINTER       :: FPTR_L(:,:)
REAL(KIND=JPRB), OPTIONAL,POINTER       :: FPTR_M(:,:)

INTEGER(KIND=JPIM) :: ISTART, IEND, IPOINTS, I2D, ILEVELS
REAL(KIND=JPRB), POINTER :: ZNEC_WORKAROUND(:) 
LOGICAL :: LL_WANTED,LLHDERS
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE FMAP_2D

SUBROUTINE FMAP_3D(SELF, KBLOCK, KID, FPTR,LDHDERS,FPTR_L,FPTR_M)




CLASS(FIELD_CONTAINER_GP),TARGET, INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),       INTENT(IN)    :: KBLOCK, KID
REAL(KIND=JPRB), POINTER                :: FPTR(:,:,:)
LOGICAL,  OPTIONAL,     INTENT(IN)      :: LDHDERS
REAL(KIND=JPRB), OPTIONAL,POINTER       :: FPTR_L(:,:,:)
REAL(KIND=JPRB), OPTIONAL,POINTER       :: FPTR_M(:,:,:)


INTEGER(KIND=JPIM) :: ISTART, IEND, IPOINTS, I2D, ILEVELS,IDIM3
REAL(KIND=JPRB), POINTER :: ZNEC_WORKAROUND(:) 
LOGICAL :: LL_WANTED,LLHDERS
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE









END SUBROUTINE FMAP_3D
!=======================================================================================
SUBROUTINE FMAP_MULTI(SELF, KBLOCK, KIDS, FPTR)





CLASS(FIELD_CONTAINER_GP),TARGET,INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),       INTENT(IN)    :: KBLOCK, KIDS(:)
REAL(KIND=JPRB), POINTER                :: FPTR(:,:,:)

INTEGER(KIND=JPIM) :: ISTART, IEND, IPOINTS, I2D, ILEVELS, ID, I, IVARS, ISIZE_GFL
REAL(KIND=JPRB), POINTER :: ZNEC_WORKAROUND(:) 
LOGICAL :: LL_WANTED
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE FMAP_MULTI
!=======================================================================================
SUBROUTINE UNMAP_LAST_BLOCK(SELF, KBLOCK, KID)






CLASS(FIELD_CONTAINER_GP),TARGET, INTENT(IN)  :: SELF
INTEGER(KIND=JPIM),       INTENT(IN)  :: KBLOCK, KID

REAL(KIND=JPRB), POINTER :: FPTR(:,:) => NULL()
INTEGER(KIND=JPIM)       :: IPOINTS, I2D, ILEVELS
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE





END SUBROUTINE UNMAP_LAST_BLOCK

!=======================================================================================

FUNCTION KINDEX_OLD(SELF,KFID,KATTACH)

CLASS(FIELD_CONTAINER_GP) , INTENT(IN) :: SELF
INTEGER(KIND=JPIM),    INTENT(IN) :: KFID
INTEGER(KIND=JPIM),    INTENT(IN) :: KATTACH
INTEGER(KIND=JPIM) :: KINDEX_OLD
REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE







END FUNCTION KINDEX_OLD
!=======================================================================================

END MODULE FIELD_CONTAINER_GP_MOD
