MODULE FIELD_CONTAINER_SP_MOD
USE PARKIND1                , ONLY : JPIM, JPRB
USE YOMHOOK                 , ONLY : LHOOK, DR_HOOK, JPHOOK
USE FIELD_CONTAINER_BASE_MOD
USE FIELD_DEFINITIONS_BASE  , ONLY : FIELD_ACCESS_BASE, FIELD_METADATA_BASE

IMPLICIT NONE

PRIVATE
PUBLIC :: TYPE_ITERATOR
TYPE TYPE_FIELD_INDEX
  LOGICAL :: L_ON = .FALSE.
END TYPE TYPE_FIELD_INDEX
!!$TYPE TYPE_STORAGE_ARRAYS
!!$  REAL(KIND=JPRB),POINTER :: STORE1D(:) => NULL()
!!$  REAL(KIND=JPRB),POINTER :: STORE2D(:,:) => NULL()
!!$  REAL(KIND=JPRB),POINTER :: STORE3D(:,:,:) => NULL()
!!$END type TYPE_STORAGE_ARRAYS
!!$TYPE, PUBLIC :: TYPE_ITERATOR
!!$INTEGER :: ICURRENT=0
!!$END type TYPE_ITERATOR
TYPE,PUBLIC,EXTENDS(FIELD_CONTAINER_BASE) :: FIELD_CONTAINER_SP
  CONTAINS
  PROCEDURE :: FIELD_CREATE
  PROCEDURE :: FIELD_DESTROY
  PROCEDURE :: FIELD_OPEN_FAC
  PROCEDURE :: FIELD_CLOSE_FAC
  PROCEDURE :: FIELD_ITERATED
  PROCEDURE :: FIELD_OPEN_ONE_1D
  PROCEDURE :: FIELD_OPEN_ONE_2D
  GENERIC,PUBLIC :: FIELD_OPEN_ONE => FIELD_OPEN_ONE_1D
  GENERIC,PUBLIC :: FIELD_OPEN_ONE => FIELD_OPEN_ONE_2D
  PROCEDURE :: FIELD_CLOSE_ONE_1D
  PROCEDURE :: FIELD_CLOSE_ONE_2D
  GENERIC,PUBLIC :: FIELD_CLOSE_ONE => FIELD_CLOSE_ONE_1D
  GENERIC,PUBLIC :: FIELD_CLOSE_ONE => FIELD_CLOSE_ONE_2D
  PROCEDURE :: ZERO
END TYPE FIELD_CONTAINER_SP

CONTAINS
!=======================================================================================
SUBROUTINE FIELD_CREATE(SELF,NAMESPACE,KPOINTS,KLEVELS,KFIDS,KATTACH)
CLASS(FIELD_CONTAINER_SP), INTENT(INOUT) :: SELF
CLASS(FIELD_METADATA_BASE),   INTENT(IN)    :: NAMESPACE  
INTEGER(KIND=JPIM),           INTENT(IN)    :: KPOINTS    
INTEGER(KIND=JPIM),           INTENT(IN)    :: KLEVELS(:) 
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: KFIDS(:)    
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: KATTACH     

INTEGER(KIND=JPIM) :: ID
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE






END SUBROUTINE FIELD_CREATE
!===============================================================================
SUBROUTINE FIELD_DESTROY(SELF)
CLASS(FIELD_CONTAINER_SP), INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM) :: ID
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE FIELD_DESTROY
!===============================================================================
SUBROUTINE FIELD_OPEN_FAC(SELF, KFIDS, FAC)
CLASS(FIELD_CONTAINER_SP), INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM), TARGET, OPTIONAL,INTENT(IN) :: KFIDS(:)
CLASS(FIELD_ACCESS_BASE),           INTENT(OUT) :: FAC

INTEGER(KIND=JPIM) :: IFIELDS_USED,ID,J
INTEGER(KIND=JPIM),ALLOCATABLE :: IUSED_FIDS(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
































END SUBROUTINE FIELD_OPEN_FAC
!===============================================================================

!===============================================================================
SUBROUTINE MAP_NAMES_TO_STORAGE(SELF, KFIDS, MFAC, LD_RELEASE)
CLASS(FIELD_CONTAINER_SP),TARGET,INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),            INTENT(IN)    :: KFIDS(:)
CLASS(FIELD_ACCESS_BASE), OPTIONAL, INTENT(INOUT) :: MFAC
LOGICAL, OPTIONAL,             INTENT(IN)    :: LD_RELEASE 
REAL(KIND=JPRB), POINTER :: FIELD_1D(:)
REAL(KIND=JPRB), POINTER :: FIELD_2D(:,:)
REAL(KIND=JPRB), POINTER :: FIELD_3D(:,:,:)
INTEGER(KIND=JPIM)       :: ID,INFIDS,J
LOGICAL :: LL_NULLIFY
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE MAP_NAMES_TO_STORAGE
!===============================================================================
SUBROUTINE FIELD_CLOSE_FAC(SELF, FAC)
CLASS(FIELD_CONTAINER_SP), INTENT(INOUT) :: SELF
CLASS(FIELD_ACCESS_BASE),    INTENT(INOUT) :: FAC

INTEGER(KIND=JPIM) :: J,ID,INFIDS
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE






END SUBROUTINE FIELD_CLOSE_FAC
!===============================================================================
FUNCTION FIELD_ITERATED(SELF, ITERATOR,KFIDS, FIELD_1D, FIELD_2D,KOTID)
INTEGER(KIND=JPIM) :: FIELD_ITERATED
CLASS(FIELD_CONTAINER_SP),TARGET, INTENT(IN) :: SELF
TYPE(TYPE_ITERATOR), INTENT(INOUT) :: ITERATOR
INTEGER(KIND=JPIM), OPTIONAL, TARGET,INTENT(IN)    :: KFIDS(:)    
REAL(KIND=JPRB), POINTER, OPTIONAL, INTENT(OUT)     :: FIELD_1D(:)   
REAL(KIND=JPRB), POINTER, OPTIONAL, INTENT(OUT)     :: FIELD_2D(:,:) 
INTEGER(KIND=JPIM), OPTIONAL,         INTENT(OUT)   :: KOTID         

INTEGER(KIND=JPIM), POINTER :: IUSE_FIDS(:)
INTEGER(KIND=JPIM) :: INO_FLDS_ITER,ID
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END FUNCTION FIELD_ITERATED



SUBROUTINE FIELD_OPEN_ONE_1D(SELF, KFID, PFIELD)





CLASS(FIELD_CONTAINER_SP),      INTENT(IN) :: SELF
INTEGER(KIND=JPIM),         INTENT(IN)    :: KFID      
REAL(KIND=JPRB), POINTER, INTENT(OUT)     :: PFIELD(:)

INTEGER(KIND=JPIM) :: IFIDS(1)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE










END SUBROUTINE FIELD_OPEN_ONE_1D
!=======================================================================================
SUBROUTINE FIELD_OPEN_ONE_2D(SELF, KFID, PFIELD)

CLASS(FIELD_CONTAINER_SP),        INTENT(IN) :: SELF
INTEGER(KIND=JPIM),           INTENT(IN)    :: KFID 
REAL(KIND=JPRB), POINTER, INTENT(OUT)       :: PFIELD(:,:)

INTEGER(KIND=JPIM) :: IFIDS(1)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE FIELD_OPEN_ONE_2D
!=======================================================================================
SUBROUTINE FIELD_CLOSE_ONE_1D(SELF, KFID, PFIELD)




CLASS(FIELD_CONTAINER_SP), INTENT(IN)    :: SELF
INTEGER(KIND=JPIM),        INTENT(IN)    :: KFID 
REAL(KIND=JPRB), POINTER,  INTENT(INOUT) :: PFIELD(:)

INTEGER(KIND=JPIM) :: IFIDS(1)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE FIELD_CLOSE_ONE_1D
!=======================================================================================
SUBROUTINE FIELD_CLOSE_ONE_2D(SELF, KFID, PFIELD)

CLASS(FIELD_CONTAINER_SP), INTENT(IN)    :: SELF
INTEGER(KIND=JPIM),        INTENT(IN)    :: KFID 
REAL(KIND=JPRB), POINTER,  INTENT(INOUT) :: PFIELD(:,:)

INTEGER(KIND=JPIM) :: IFIDS(1)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE







END SUBROUTINE FIELD_CLOSE_ONE_2D
!=======================================================================================
SUBROUTINE FMAP_1D(SELF, KFID, PFIELD)
CLASS(FIELD_CONTAINER_SP),TARGET,INTENT(IN) :: SELF
INTEGER(KIND=JPIM),           INTENT(IN)    :: KFID 
REAL(KIND=JPRB), POINTER, INTENT(OUT)       :: PFIELD(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE




END SUBROUTINE FMAP_1D
!=======================================================================================
SUBROUTINE FMAP_2D(SELF, KFID, PFIELD)
CLASS(FIELD_CONTAINER_SP),TARGET,INTENT(IN) :: SELF
INTEGER(KIND=JPIM),           INTENT(IN)    :: KFID 
REAL(KIND=JPRB), POINTER, INTENT(OUT)       :: PFIELD(:,:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE




END SUBROUTINE FMAP_2D
!=======================================================================================
SUBROUTINE ZERO(SELF)
CLASS(FIELD_CONTAINER_SP),        INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM) :: ID
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE




END SUBROUTINE ZERO
!=======================================================================================
END MODULE FIELD_CONTAINER_SP_MOD
