
MODULE MF_PHYS_SURFACE_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE SURFACE_VARIABLES_MOD, ONLY: SURFACE_VARIABLES
USE SURFACE_VIEWS_MODULE
USE YOMDYN, ONLY : TDYN

IMPLICIT NONE

TYPE MF_PHYS_SURF_TYPE
  ! --------------------------------------
  ! ----  Surface field group views  -----
  TYPE(SURFACE_VIEW_GROUP_SOILB) :: GSP_SB
  TYPE(SURFACE_VIEW_GROUP_SNOWG) :: GSP_SG
  TYPE(SURFACE_VIEW_GROUP_LAKEB) :: GSP_SL
  TYPE(SURFACE_VIEW_GROUP_RESVR) :: GSP_RR
  TYPE(SURFACE_VIEW_GROUP_CLS) :: GSP_CL
  TYPE(SURFACE_VIEW_GROUP_OML) :: GSP_OM
  TYPE(SURFACE_VIEW_GROUP_EXTRP) :: GSP_EP
  TYPE(SURFACE_VIEW_GROUP_XTRP2) :: GSP_X2
  TYPE(SURFACE_VIEW_GROUP_CANRI) :: GSP_CI
  TYPE(SURFACE_VIEW_GROUP_VARSF) :: GSD_VF
  TYPE(SURFACE_VIEW_GROUP_VCLIH) :: GSD_VH
  TYPE(SURFACE_VIEW_GROUP_VCLIK) :: GSD_VK
  TYPE(SURFACE_VIEW_GROUP_VCLIP) :: GSD_VP
  TYPE(SURFACE_VIEW_GROUP_VCLIV) :: GSD_VV
  TYPE(SURFACE_VIEW_GROUP_VCLIA) :: GSD_VA
  TYPE(SURFACE_VIEW_GROUP_VCLIN) :: GSD_VN
  TYPE(SURFACE_VIEW_GROUP_VDIAGO2) :: GSD_V2
  TYPE(SURFACE_VIEW_GROUP_VDIAGO3) :: GSD_V3
  TYPE(SURFACE_VIEW_GROUP_VDIAG) :: GSD_VD
  TYPE(SURFACE_VIEW_GROUP_SATSIM) :: GSD_SM
  TYPE(SURFACE_VIEW_GROUP_WAVES) :: GSD_WS
  TYPE(SURFACE_VIEW_GROUP_WAM) :: GSD_WW
  TYPE(SURFACE_VIEW_GROUP_PRECFRAC) :: GSD_PF
  TYPE(SURFACE_VIEW_GROUP_VEXTRA) :: GSD_XA
  TYPE(SURFACE_VIEW_GROUP_VEXTRDI) :: GSD_DI
  TYPE(SURFACE_VIEW_GROUP_VPRECIP) :: GSD_XP
  TYPE(SURFACE_VIEW_GROUP_VPRECIP2) :: GSD_XP2
  TYPE(SURFACE_VIEW_GROUP_VEXTR2) :: GSD_X2
  TYPE(SURFACE_VIEW_GROUP_SFORC) :: GSD_SFO
  TYPE(SURFACE_VIEW_GROUP_SFLUX) :: GSD_SFL
  TYPE(SURFACE_VIEW_GROUP_VO3ABC) :: GSD_VC

CONTAINS
  PROCEDURE :: INIT => MF_PHYS_SURF_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => MF_PHYS_SURF_TYPE_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => MF_PHYS_SURF_TYPE_SET9TO0
  PROCEDURE :: SET1TO9 => MF_PHYS_SURF_TYPE_SET1TO9
  PROCEDURE :: SET1TO0 => MF_PHYS_SURF_TYPE_SET1TO0
  PROCEDURE :: SET0TO1 => MF_PHYS_SURF_TYPE_SET0TO1
  PROCEDURE :: PHTFILT => MF_PHYS_SURF_TYPE_PHTFILT
  PROCEDURE :: FINAL => MF_PHYS_SURF_TYPE_FINAL
END TYPE MF_PHYS_SURF_TYPE


CONTAINS

  SUBROUTINE MF_PHYS_SURF_TYPE_INIT(SELF, SURFVARS)
    CLASS(MF_PHYS_SURF_TYPE) :: SELF
    TYPE(SURFACE_VARIABLES), TARGET, INTENT(INOUT) :: SURFVARS

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

  END SUBROUTINE MF_PHYS_SURF_TYPE_INIT

  SUBROUTINE MF_PHYS_SURF_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    
    CLASS(MF_PHYS_SURF_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

  END SUBROUTINE MF_PHYS_SURF_TYPE_UPDATE_VIEW

  SUBROUTINE MF_PHYS_SURF_TYPE_SET9TO0(SELF)
    
    CLASS(MF_PHYS_SURF_TYPE) :: SELF

    
    
    
    
    
    
    
    
    
  END SUBROUTINE MF_PHYS_SURF_TYPE_SET9TO0

  SUBROUTINE MF_PHYS_SURF_TYPE_SET1TO9(SELF)
    
    CLASS(MF_PHYS_SURF_TYPE) :: SELF

    
    
    
    
    
    
    
    
    
  END SUBROUTINE MF_PHYS_SURF_TYPE_SET1TO9

  SUBROUTINE MF_PHYS_SURF_TYPE_SET1TO0(SELF)
    
    CLASS(MF_PHYS_SURF_TYPE) :: SELF

    
    
    
    
    
    
    
    
    
  END SUBROUTINE MF_PHYS_SURF_TYPE_SET1TO0

  SUBROUTINE MF_PHYS_SURF_TYPE_SET0TO1(SELF)
    
    CLASS(MF_PHYS_SURF_TYPE) :: SELF

    
    
    
    
    
    
    
    
    
  END SUBROUTINE MF_PHYS_SURF_TYPE_SET0TO1

  SUBROUTINE MF_PHYS_SURF_TYPE_PHTFILT(SELF, YDDYN)
    
    CLASS(MF_PHYS_SURF_TYPE) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN

    
    
    
    
    
    
    
    
    
  END SUBROUTINE MF_PHYS_SURF_TYPE_PHTFILT

  SUBROUTINE MF_PHYS_SURF_TYPE_FINAL(SELF)
    
    CLASS(MF_PHYS_SURF_TYPE) :: SELF

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

  END SUBROUTINE MF_PHYS_SURF_TYPE_FINAL

END MODULE MF_PHYS_SURFACE_TYPE_MOD
