MODULE MODEL_PHYSICS_GENERAL_MOD
  USE YOMDPHY , ONLY : TDPHY
  USE YOMSLPHY, ONLY : TSLPHY
  USE YOEVDF,   ONLY : TVDF
  IMPLICIT NONE
  
  TYPE MODEL_PHYSICS_GENERAL_TYPE

    TYPE(TDPHY)  :: YRDPHY   !! dimensions
    TYPE(TSLPHY) :: YRSLPHY  !! physics & dynamics interfacing
    TYPE(TVDF)   :: YRVDF
  
  CONTAINS
  
    PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 

  END TYPE MODEL_PHYSICS_GENERAL_TYPE

  !---------------------------------------------------------------------

  CONTAINS 

  SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
  
  CLASS(MODEL_PHYSICS_GENERAL_TYPE), INTENT(IN) :: SELF
  INTEGER                          , INTENT(IN) :: KDEPTH
  INTEGER                          , INTENT(IN) :: KOUTNO

  
  
  
  

  END SUBROUTINE PRINT_CONFIGURATION

END MODULE MODEL_PHYSICS_GENERAL_MOD
