
!!=================================

MODULE MODEL_PHYSICS_STOCHAST_MOD
  USE STOPH_MIX        , ONLY : TSTOPH
  USE YOMRANDOM_STREAMS, ONLY : TRANDOM_STREAMS
  IMPLICIT NONE

  TYPE MODEL_PHYSICS_STOCHAST_TYPE

  TYPE(TSTOPH)          :: YRSTOPH
  TYPE(TRANDOM_STREAMS) :: YR_RANDOM_STREAMS

    CONTAINS

    PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 

  END TYPE MODEL_PHYSICS_STOCHAST_TYPE

  !---------------------------------------------------------------------

  CONTAINS 

  SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
  
  CLASS(MODEL_PHYSICS_STOCHAST_TYPE), INTENT(IN) :: SELF
  INTEGER                           , INTENT(IN) :: KDEPTH
  INTEGER                           , INTENT(IN) :: KOUTNO

  
  
  

  END SUBROUTINE PRINT_CONFIGURATION

END MODULE MODEL_PHYSICS_STOCHAST_MOD


