MODULE MODEL_CHEM_MOD
  USE YOMOZO  , ONLY : TOZO
  USE YOMCHEM , ONLY : TCHEM
  USE YOMCOMPO, ONLY : TCOMPO
  IMPLICIT NONE

  TYPE MODEL_CHEM_TYPE

    TYPE(TOZO)   :: YROZO
    TYPE(TCHEM)  :: YRCHEM
    TYPE(TCOMPO) :: YRCOMPO

    CONTAINS

    PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 

  END TYPE MODEL_CHEM_TYPE

  !---------------------------------------------------------------------

  CONTAINS 

  SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
  
  CLASS(MODEL_CHEM_TYPE), INTENT(IN) :: SELF
  INTEGER               , INTENT(IN) :: KDEPTH
  INTEGER               , INTENT(IN) :: KOUTNO

  

  END SUBROUTINE PRINT_CONFIGURATION

END MODULE MODEL_CHEM_MOD
