INTERFACE
SUBROUTINE ACCLDIA(YDCST, LDXCLP, LDXTGST, LDXXGST,YDPHY,YDPHY2,YDTOPH,KIDIA,KFDIA,KLON,KLEV,&
 & PUCLS,PVCLS,PU,PV,PCAPE,PDCAPE,PTKE,PAPHIFM,POROG,&
 & PUGST,PVGST,PBLH,KCLPH) 

IMPORT

TYPE(TPHY) ,INTENT(IN):: YDPHY
TYPE(TPHY2) ,INTENT(IN):: YDPHY2
TYPE(TTOPH) ,INTENT(IN):: YDTOPH
TYPE(TCST) ,INTENT(IN):: YDCST
LOGICAL ,INTENT(IN):: LDXCLP
LOGICAL ,INTENT(IN):: LDXTGST
LOGICAL ,INTENT(IN):: LDXXGST
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA,KFDIA,KLON,KLEV
REAL(KIND=JPRB), INTENT(IN) :: PUCLS(KLON), PVCLS(KLON), POROG(KLON)
REAL(KIND=JPRB), INTENT(OUT) :: PUGST(KLON), PVGST(KLON), PBLH(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PTKE(KLON,KLEV), PAPHIFM(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PU(KLON,KLEV), PV(KLON,KLEV), PCAPE(KLON), PDCAPE(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCLPH(KLON)
END SUBROUTINE ACCLDIA
END INTERFACE
