INTERFACE
SUBROUTINE APL_ARPEGE_INIT_SURFEX (YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS,&
 & YDCPG_MISC, YDCPG_GPAR, YDMF_PHYS, YDVARS, YDMODEL, PALBD, PALBP, PFLU_EMIS, PSGROUPEL, PSRAIN,&
 & PSSNOW, PTSN) 

IMPORT

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT(IN) :: YDMF_PHYS_BASE_STATE
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
TYPE(CPG_MISC_TYPE), INTENT(INOUT) :: YDCPG_MISC
TYPE(CPG_GPAR_TYPE), INTENT(INOUT) :: YDCPG_GPAR
TYPE(MF_PHYS_TYPE), INTENT(INOUT) :: YDMF_PHYS
TYPE(FIELD_VARIABLES), INTENT(INOUT) :: YDVARS
TYPE(MODEL), INTENT(IN) :: YDMODEL
REAL(KIND=JPRB), INTENT(OUT) :: PALBD(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB), INTENT(OUT) :: PALBP(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB), INTENT(OUT) :: PFLU_EMIS (YDCPG_OPTS%KLON)
REAL(KIND=JPRB), INTENT(OUT) :: PSGROUPEL(YDCPG_OPTS%KLON)
REAL(KIND=JPRB), INTENT(OUT) :: PSRAIN(YDCPG_OPTS%KLON)
REAL(KIND=JPRB), INTENT(OUT) :: PSSNOW(YDCPG_OPTS%KLON)
REAL(KIND=JPRB), INTENT(OUT) :: PTSN(YDCPG_OPTS%KLON)
END SUBROUTINE APL_ARPEGE_INIT_SURFEX
END INTERFACE
