INTERFACE
SUBROUTINE APL_ARPEGE_SURFACE_UPDATE (YDCPG_BNDS, YDCPG_OPTS, YDCPG_GPAR, YDMF_PHYS, YDMF_PHYS_SURF,&
 & YDMODEL, LDCONFX, PDTPHY, PDSA_C1, PDSA_C2, PFLU_FEVI, PFLU_VEG) 

IMPORT

TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
TYPE(CPG_GPAR_TYPE), INTENT(INOUT) :: YDCPG_GPAR
TYPE(MF_PHYS_TYPE), INTENT(INOUT) :: YDMF_PHYS
TYPE(MF_PHYS_SURF_TYPE), INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(MODEL), INTENT(IN) :: YDMODEL
LOGICAL, INTENT(IN) :: LDCONFX
REAL(KIND=JPRB), INTENT(IN) :: PDTPHY
REAL(KIND=JPRB), INTENT(IN) :: PDSA_C1 (YDCPG_OPTS%KLON)
REAL(KIND=JPRB), INTENT(IN) :: PDSA_C2 (YDCPG_OPTS%KLON)
REAL(KIND=JPRB), INTENT(IN) :: PFLU_FEVI (YDCPG_OPTS%KLON,YDCPG_OPTS%KTSSG+1)
REAL(KIND=JPRB), INTENT(IN) :: PFLU_VEG (YDCPG_OPTS%KLON)
END SUBROUTINE APL_ARPEGE_SURFACE_UPDATE
END INTERFACE
