INTERFACE
SUBROUTINE APL_ARPEGE_ALBEDO_COMPUTATION (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS,&
 & YDMF_PHYS_SURF, YDMODEL, PALBD, PALBP, PEPS0, PFLU_EMIS, PFLU_NEIJ, PRDG_MU0) 

IMPORT

TYPE(MF_PHYS_BASE_STATE_TYPE), INTENT(IN) :: YDMF_PHYS_BASE_STATE
TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
TYPE(MF_PHYS_TYPE), INTENT(INOUT) :: YDMF_PHYS
TYPE(MF_PHYS_SURF_TYPE), INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(MODEL), INTENT(IN) :: YDMODEL
REAL(KIND=JPRB), INTENT(OUT) :: PALBD(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB), INTENT(OUT) :: PALBP(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB), INTENT(IN) :: PEPS0
REAL(KIND=JPRB), INTENT(OUT) :: PFLU_EMIS (YDCPG_OPTS%KLON)
REAL(KIND=JPRB), INTENT(IN) :: PFLU_NEIJ (YDCPG_OPTS%KLON)
REAL(KIND=JPRB), INTENT(IN) :: PRDG_MU0 (YDCPG_OPTS%KLON)
END SUBROUTINE APL_ARPEGE_ALBEDO_COMPUTATION
END INTERFACE
