INTERFACE
SUBROUTINE APL_ARPEGE_AEROSOLS_FOR_RADIATION (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS,&
 & YDMF_PHYS_SURF, YDMODEL, PAER, PAERINDS) 

IMPORT 

TYPE(MF_PHYS_BASE_STATE_TYPE), INTENT(IN) :: YDMF_PHYS_BASE_STATE
TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
TYPE(MF_PHYS_SURF_TYPE), INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(MODEL), INTENT(IN) :: YDMODEL
REAL(KIND=JPRB), INTENT(OUT) :: PAER(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,6)
REAL(KIND=JPRB), INTENT(OUT) :: PAERINDS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
END SUBROUTINE APL_ARPEGE_AEROSOLS_FOR_RADIATION
END INTERFACE
