INTERFACE
SUBROUTINE CHECKMV(KINDAT, YDCST, YDRIP,YDPHY0,YDPHY2,KIDIA,KFDIA,KLON,KLEV,KSTEP,PAPHI,PAPHIF&
 & ,PAPRS,PAPRSF,PGELAM,PGEMU,PMU0,PLSM,PT,PQ,PTS) 

IMPORT

INTEGER(KIND=JPIM) ,INTENT(IN) :: KINDAT
TYPE(TPHY0) ,INTENT(IN) :: YDPHY0
TYPE(TPHY2) ,INTENT(IN) :: YDPHY2
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TRIP) ,INTENT(IN) :: YDRIP
INTEGER(KIND=JPIM) ,INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLON
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTEP
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEMU(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PMU0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
END SUBROUTINE CHECKMV
END INTERFACE
