MODULE CPG_TYPE_MOD

USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_REGISTRY_MOD
USE PARKIND1, ONLY : JPRB, JPIM, JPIB
USE YOM_YGFL, ONLY : TYPE_GFL_COMP

IMPLICIT NONE

TYPE CPG_XYBDER_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()
  INTEGER (KIND=JPIM) :: IP_LNPRL = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LNPRL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: LNPRL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_LNPRL => NULL ()
  INTEGER (KIND=JPIM) :: IP_LNPRM = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LNPRM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: LNPRM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_LNPRM => NULL ()
  INTEGER (KIND=JPIM) :: IP_ALPHL = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALPHL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ALPHL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_ALPHL => NULL ()
  INTEGER (KIND=JPIM) :: IP_ALPHM = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALPHM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ALPHM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_ALPHM => NULL ()
  INTEGER (KIND=JPIM) :: IP_ALPHPLL = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALPHPLL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ALPHPLL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_ALPHPLL => NULL ()
  INTEGER (KIND=JPIM) :: IP_ALPHPLM = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALPHPLM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ALPHPLM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_ALPHPLM => NULL ()
  INTEGER (KIND=JPIM) :: IP_COEFD = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: COEFD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: COEFD (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_COEFD => NULL ()
  INTEGER (KIND=JPIM) :: IP_COEFA = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: COEFA (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: COEFA (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_COEFA => NULL ()
  INTEGER (KIND=JPIM) :: IP_COEFAPL = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: COEFAPL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: COEFAPL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_COEFAPL => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_XYBDER_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_XYBDER_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_XYBDER_TYPE_FINAL
END TYPE CPG_XYBDER_TYPE

TYPE CPG_XYB_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()
  INTEGER (KIND=JPIM) :: IP_DELP = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DELP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DELP (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_DELP => NULL ()
  INTEGER (KIND=JPIM) :: IP_RDELP = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RDELP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RDELP (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RDELP => NULL ()
  INTEGER (KIND=JPIM) :: IP_LNPR = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LNPR (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: LNPR (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_LNPR => NULL ()
  INTEGER (KIND=JPIM) :: IP_ALPH = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALPH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ALPH (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_ALPH => NULL ()
  INTEGER (KIND=JPIM) :: IP_RTGR = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RTGR (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RTGR (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RTGR => NULL ()
  INTEGER (KIND=JPIM) :: IP_RPRE = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RPRE (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RPRE (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RPRE => NULL ()
  INTEGER (KIND=JPIM) :: IP_RPP = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RPP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RPP (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RPP => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_XYB_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_XYB_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_XYB_TYPE_FINAL
END TYPE CPG_XYB_TYPE

TYPE CPG_HWIND_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()
  INTEGER (KIND=JPIM) :: IP_UH = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: UH (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_UH => NULL ()
  INTEGER (KIND=JPIM) :: IP_VH = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: VH (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_VH => NULL ()
  INTEGER (KIND=JPIM) :: IP_WWI = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: WWI (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: WWI (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_WWI => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_HWIND_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_HWIND_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_HWIND_TYPE_FINAL
END TYPE CPG_HWIND_TYPE

TYPE CPG_RCP_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()
  INTEGER (KIND=JPIM) :: IP_CP = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: CP (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_CP => NULL ()
  INTEGER (KIND=JPIM) :: IP_R = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: R (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: R (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_R => NULL ()
  INTEGER (KIND=JPIM) :: IP_KAP = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: KAP (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_KAP => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_RCP_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_RCP_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_RCP_TYPE_FINAL
END TYPE CPG_RCP_TYPE

TYPE CPG_CTY_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()
  INTEGER (KIND=JPIM) :: IP_EVEL = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EVEL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: EVEL (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_EVEL => NULL ()
  INTEGER (KIND=JPIM) :: IP_VVEL = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VVEL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: VVEL (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_VVEL => NULL ()
  INTEGER (KIND=JPIM) :: IP_PSDIV = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PSDIV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PSDIV (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PSDIV => NULL ()
  INTEGER (KIND=JPIM) :: IP_PSDVBC = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PSDVBC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PSDVBC (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PSDVBC => NULL ()
  INTEGER (KIND=JPIM) :: IP_DIVDP = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIVDP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DIVDP (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_DIVDP => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_CTY_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_CTY_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_CTY_TYPE_FINAL
END TYPE CPG_CTY_TYPE

TYPE CPG_TND_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDU = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDU (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDU (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDU => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDV = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDV (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDV => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDU_NOC = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDU_NOC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDU_NOC (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDU_NOC => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDV_NOC = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDV_NOC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDV_NOC (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDV_NOC => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDT = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDT (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDT (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDT => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDPD = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDPD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDPD (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDPD => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDVD = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDVD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDVD (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDVD => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDGW = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDGW (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDGW (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDGW => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_TND_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_TND_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_TND_TYPE_FINAL
END TYPE CPG_TND_TYPE

TYPE CPG_GPAR_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_DATA => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: INPRR (:) => NULL ()
!>REAL (KIND=JPRB)                      :: INPRR (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_INPRR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: INPRS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: INPRS (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_INPRS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: INPRG (:) => NULL ()
!>REAL (KIND=JPRB)                      :: INPRG (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_INPRG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ACPRR (:) => NULL ()
!>REAL (KIND=JPRB)                      :: ACPRR (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_ACPRR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ACPRS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: ACPRS (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_ACPRS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ACPRG (:) => NULL ()
!>REAL (KIND=JPRB)                      :: ACPRG (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_ACPRG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALBDIR (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ALBDIR (NPROMA, 1:YDCPG_OPTS%KSW)
  CLASS (FIELD_3RB), POINTER :: F_ALBDIR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALBSCA (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ALBSCA (NPROMA, 1:YDCPG_OPTS%KSW)
  CLASS (FIELD_3RB), POINTER :: F_ALBSCA => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RAIN (:) => NULL ()
!>REAL (KIND=JPRB)                      :: RAIN (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_RAIN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SNOW (:) => NULL ()
!>REAL (KIND=JPRB)                      :: SNOW (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_SNOW => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GZ0 (:) => NULL ()
!>REAL (KIND=JPRB)                      :: GZ0 (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_GZ0 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GZ0H (:) => NULL ()
!>REAL (KIND=JPRB)                      :: GZ0H (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_GZ0H => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VQS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: VQS (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_VQS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VTS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: VTS (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_VTS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VEMIS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: VEMIS (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_VEMIS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SWDIR (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: SWDIR (NPROMA, 1:YDCPG_OPTS%KSW)
  CLASS (FIELD_3RB), POINTER :: F_SWDIR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SWDIF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: SWDIF (NPROMA, 1:YDCPG_OPTS%KSW)
  CLASS (FIELD_3RB), POINTER :: F_SWDIF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LSM (:) => NULL ()
!>REAL (KIND=JPRB)                      :: LSM (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_LSM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CD (:) => NULL ()
!>REAL (KIND=JPRB)                      :: CD (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_CD => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_GPAR_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_GPAR_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_GPAR_TYPE_FINAL
END TYPE CPG_GPAR_TYPE

TYPE CPG_DYN_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: OROGL (:) => NULL ()
!>REAL (KIND=JPRB)                      :: OROGL (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_OROGL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: OROGM (:) => NULL ()
!>REAL (KIND=JPRB)                      :: OROGM (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_OROGM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PHI (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PHI (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PHI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PRE (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PRE (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PRE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PHIF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PHIF (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PHIF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PREF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PREF (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PREF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PREL (:) => NULL ()
!>REAL (KIND=JPRB)                      :: PREL (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_PREL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PREM (:) => NULL ()
!>REAL (KIND=JPRB)                      :: PREM (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_PREM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NHY (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: NHY (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_NHY => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWFT (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GWFT (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_GWFT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KENE (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: KENE (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_KENE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NHX (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: NHX (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_NHX => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PHIFL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PHIFL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PHIFL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PHIFM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PHIFM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PHIFM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RTL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RTL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RTL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RTM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RTM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RTM => NULL ()
  TYPE (CPG_RCP_TYPE) :: RCP
  TYPE (CPG_CTY_TYPE) :: CTY
  TYPE (CPG_HWIND_TYPE) :: UVH
  TYPE (CPG_XYB_TYPE) :: XYB
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DBBC (:) => NULL ()
!>REAL (KIND=JPRB)                      :: DBBC (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_DBBC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: GWS (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_GWS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWFL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GWFL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_GWFL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWFM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GWFM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_GWFM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWT (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GWT (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_GWT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NHPREF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: NHPREF (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_NHPREF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NHPREH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: NHPREH (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_NHPREH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QCHAL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QCHAL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_QCHAL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QCHAM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QCHAM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_QCHAM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RDPHI (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RDPHI (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RDPHI => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_DYN_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_DYN_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_DYN_TYPE_FINAL
END TYPE CPG_DYN_TYPE

TYPE CPG_PHY_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PRE (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PRE (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PRE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PREF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PREF (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PREF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PREHYD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PREHYD (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PREHYD => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PREHYDF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PREHYDF (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PREHYDF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: WL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: WL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_WL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: WM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: WM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_WM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: W (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: W (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_W => NULL ()
  TYPE (CPG_XYB_TYPE) :: XYB

CONTAINS
  PROCEDURE :: INIT => CPG_PHY_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_PHY_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_PHY_TYPE_FINAL
END TYPE CPG_PHY_TYPE

TYPE CPG_MISC_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NEB (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: NEB (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_NEB => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QLI (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QLI (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_QLI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QICE (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QICE (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_QICE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QRAIN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QRAIN (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_QRAIN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QSNOW (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QSNOW (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_QSNOW => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QGRAUPEL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QGRAUPEL (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_QGRAUPEL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RH (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_RH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: QS (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_QS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QSOL (:) => NULL ()
!>REAL (KIND=JPRB)                      :: QSOL (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_QSOL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DHSF (:) => NULL ()
!>REAL (KIND=JPRB)                      :: DHSF (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_DHSF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CLCT (:) => NULL ()
!>REAL (KIND=JPRB)                      :: CLCT (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_CLCT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LSM (:) => NULL ()
!>REAL (KIND=JPRB)                      :: LSM (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_LSM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TSOL (:) => NULL ()
!>REAL (KIND=JPRB)                      :: TSOL (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_TSOL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FTCNS (:, :, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FTCNS (NPROMA, 0:YDCPG_OPTS%KFLEVG, 1:6)
  CLASS (FIELD_4RB), POINTER :: F_FTCNS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KOZO (:, :, :) => NULL ()
!>REAL (KIND=JPRB)                      :: KOZO (NPROMA, 1:YDCPG_OPTS%KFLEVG, 1:YDCPG_OPTS%KVCLIS)
  CLASS (FIELD_4RB), POINTER :: F_KOZO => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_MISC_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_MISC_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_MISC_TYPE_FINAL
END TYPE CPG_MISC_TYPE

TYPE CPG_DDH_TYPE
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: AUX3D (:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_AUX3D => NULL ()
  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: AUX2D (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_AUX2D => NULL ()

  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DHCV  (:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DHCV => NULL ()
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: AUXSM (:,:,:,:) => NULL ()
  CLASS (FIELD_5RB), POINTER :: F_AUXSM => NULL ()
  INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: DDHI (:) => NULL ()
  CLASS (FIELD_2IM), POINTER :: F_DDHI => NULL ()
CONTAINS
  PROCEDURE :: INIT => CPG_DDH_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_DDH_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_DDH_TYPE_FINAL
END TYPE CPG_DDH_TYPE





TYPE CPG_SL1_2D_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_P => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_F (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_P_F => NULL ()




  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_SPF (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_P_SPF => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_SP (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_P_SP => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_P (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_P_P => NULL ()

END TYPE

TYPE CPG_SL1_3D_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_F (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P_F => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_SPF (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P_SPF => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_SP (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P_SP => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_P (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P_P => NULL ()

  TYPE (TYPE_GFL_COMP) :: YCOMP
END TYPE


ABSTRACT INTERFACE 
  LOGICAL FUNCTION FUN_GREP (YDCOMP, YDMODEL)
    USE YOM_YGFL, ONLY : TYPE_GFL_COMP
    USE TYPE_MODEL, ONLY : MODEL
    TYPE (TYPE_GFL_COMP), INTENT (IN) :: YDCOMP
    TYPE (MODEL),  INTENT (IN) :: YDMODEL
  END FUNCTION
END INTERFACE

PRIVATE :: FUN_GREP, GREPVARS

TYPE CPG_SL1_TYPE
  LOGICAL :: LOWNED = .FALSE.
  INTEGER (KIND=JPIM) :: NLEV = -1
  INTEGER (KIND=JPIB) :: ISIZE = 0
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_DATA => NULL ()
  TYPE (CPG_SL1_3D_TYPE) :: U9
  TYPE (CPG_SL1_3D_TYPE) :: V9
  TYPE (CPG_SL1_3D_TYPE) :: T9
  TYPE (CPG_SL1_3D_TYPE) :: PD9
  TYPE (CPG_SL1_3D_TYPE) :: VD9
  TYPE (CPG_SL1_3D_TYPE) :: NHX9
  TYPE (CPG_SL1_3D_TYPE) :: UR0
  TYPE (CPG_SL1_3D_TYPE) :: VR0
  TYPE (CPG_SL1_3D_TYPE) :: ZR0
  TYPE (CPG_SL1_3D_TYPE) :: WR0
  TYPE (CPG_SL1_3D_TYPE) :: UR00
  TYPE (CPG_SL1_3D_TYPE) :: VR00
  TYPE (CPG_SL1_3D_TYPE) :: ZR00
  TYPE (CPG_SL1_3D_TYPE) :: WR00
  TYPE (CPG_SL1_3D_TYPE) :: WRA
  TYPE (CPG_SL1_3D_TYPE) :: UR9
  TYPE (CPG_SL1_3D_TYPE) :: VR9
  TYPE (CPG_SL1_3D_TYPE) :: DBBC9
  TYPE (CPG_SL1_3D_TYPE) :: DPHI9
  TYPE (CPG_SL1_2D_TYPE) :: GWS9
  TYPE (CPG_SL1_3D_TYPE) :: U0
  TYPE (CPG_SL1_3D_TYPE) :: V0
  TYPE (CPG_SL1_3D_TYPE) :: T0
  TYPE (CPG_SL1_3D_TYPE) :: PD0
  TYPE (CPG_SL1_3D_TYPE) :: VD0
  TYPE (CPG_SL1_3D_TYPE) :: C9
  TYPE (CPG_SL1_2D_TYPE) :: SP9
  TYPE (CPG_SL1_2D_TYPE) :: SP0
  TYPE (CPG_SL1_3D_TYPE) :: C0
  TYPE (CPG_SL1_3D_TYPE) :: UP9
  TYPE (CPG_SL1_3D_TYPE) :: VP9
  TYPE (CPG_SL1_3D_TYPE) :: TP9
  TYPE (CPG_SL1_3D_TYPE) :: U9_SI
  TYPE (CPG_SL1_3D_TYPE) :: V9_SI
  TYPE (CPG_SL1_3D_TYPE) :: T9_SI
  TYPE (CPG_SL1_3D_TYPE) :: PD9_SI
  TYPE (CPG_SL1_3D_TYPE) :: VD9_SI
  TYPE (CPG_SL1_3D_TYPE) :: C9_SI
  TYPE (CPG_SL1_3D_TYPE) :: UF9
  TYPE (CPG_SL1_3D_TYPE) :: VF9
  TYPE (CPG_SL1_3D_TYPE) :: TF9
  TYPE (CPG_SL1_3D_TYPE) :: VDF9
  TYPE (CPG_SL1_3D_TYPE) :: U9_NL
  TYPE (CPG_SL1_3D_TYPE) :: V9_NL
  TYPE (CPG_SL1_3D_TYPE) :: T9_NL
  TYPE (CPG_SL1_3D_TYPE) :: PD9_NL
  TYPE (CPG_SL1_3D_TYPE) :: VD9_NL
  TYPE (CPG_SL1_3D_TYPE) :: C9_NL
  TYPE (CPG_SL1_3D_TYPE) :: ZR9
  TYPE (CPG_SL1_3D_TYPE) :: Z9
  TYPE (CPG_SL1_3D_TYPE) :: Z0
  TYPE (CPG_SL1_3D_TYPE) :: ZP9

  TYPE (CPG_SL1_3D_TYPE) :: Q
  TYPE (CPG_SL1_3D_TYPE) :: I
  TYPE (CPG_SL1_3D_TYPE) :: L
  TYPE (CPG_SL1_3D_TYPE) :: LCONV
  TYPE (CPG_SL1_3D_TYPE) :: ICONV
  TYPE (CPG_SL1_3D_TYPE) :: RCONV
  TYPE (CPG_SL1_3D_TYPE) :: SCONV
  TYPE (CPG_SL1_3D_TYPE) :: IRAD
  TYPE (CPG_SL1_3D_TYPE) :: LRAD
  TYPE (CPG_SL1_3D_TYPE) :: S
  TYPE (CPG_SL1_3D_TYPE) :: R
  TYPE (CPG_SL1_3D_TYPE) :: G
  TYPE (CPG_SL1_3D_TYPE) :: H
  TYPE (CPG_SL1_3D_TYPE) :: TKE
  TYPE (CPG_SL1_3D_TYPE) :: TTE
  TYPE (CPG_SL1_3D_TYPE) :: EFB1
  TYPE (CPG_SL1_3D_TYPE) :: EFB2
  TYPE (CPG_SL1_3D_TYPE) :: EFB3
  TYPE (CPG_SL1_3D_TYPE) :: A
  TYPE (CPG_SL1_3D_TYPE) :: O3
  TYPE (CPG_SL1_3D_TYPE) :: SRC
  TYPE (CPG_SL1_3D_TYPE) :: MXL
  TYPE (CPG_SL1_3D_TYPE) :: SHTUR
  TYPE (CPG_SL1_3D_TYPE) :: FQTUR
  TYPE (CPG_SL1_3D_TYPE) :: FSTUR
  TYPE (CPG_SL1_3D_TYPE) :: CPF
  TYPE (CPG_SL1_3D_TYPE) :: SPF
  TYPE (CPG_SL1_3D_TYPE) :: CVGQ
  TYPE (CPG_SL1_3D_TYPE) :: QVA
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: GHG (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: CHEM (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: AERO (:)
  TYPE (CPG_SL1_3D_TYPE) :: LRCH4
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: FORC (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: EZDIAG (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: ERA40 (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: NOGW (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: EMIS3D (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: EDRP (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: SLDIA (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: AERAOT (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: AERLISI (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: AEROUT (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: AEROCLIM (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: UVP (:)
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: PHYS (:)
  TYPE (CPG_SL1_3D_TYPE) :: PHYCTY
  TYPE (CPG_SL1_3D_TYPE) :: RSPEC
  TYPE (CPG_SL1_3D_TYPE) :: SDSAT
  TYPE (CPG_SL1_3D_TYPE) :: CVV
  TYPE (CPG_SL1_3D_TYPE) :: RKTH
  TYPE (CPG_SL1_3D_TYPE) :: RKTQV
  TYPE (CPG_SL1_3D_TYPE) :: RKTQC
  TYPE (CPG_SL1_3D_TYPE) :: UOM
  TYPE (CPG_SL1_3D_TYPE) :: UAL
  TYPE (CPG_SL1_3D_TYPE) :: DOM
  TYPE (CPG_SL1_3D_TYPE) :: DAL
  TYPE (CPG_SL1_3D_TYPE) :: UEN
  TYPE (CPG_SL1_3D_TYPE) :: UNEBH
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: LIMA (:)
  TYPE (CPG_SL1_3D_TYPE) :: FSD
  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: EXT (:)

  TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: GFL (:)
CONTAINS
  PROCEDURE :: INIT => CPG_SL1_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_SL1_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_SL1_TYPE_FINAL
  PROCEDURE :: ZERO => CPG_SL1_TYPE_ZERO
END TYPE CPG_SL1_TYPE

TYPE CPG_SL2_TYPE
  LOGICAL :: LOWNED = .FALSE.
  INTEGER (KIND=JPIM) :: NLEV = -1
  INTEGER (KIND=JPIB) :: ISIZE = 0
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_DATA => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DBBC1 (:) => NULL ()
!>REAL (KIND=JPRB)                      :: DBBC1 (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_DBBC1 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DPHI1 (:) => NULL ()
!>REAL (KIND=JPRB)                      :: DPHI1 (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_DPHI1 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: USI (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: USI (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_USI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VSI (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: VSI (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_VSI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TSI (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: TSI (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_TSI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PDSI (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: PDSI (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_PDSI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VDSI (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: VDSI (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_VDSI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SPSI (:) => NULL ()
!>REAL (KIND=JPRB)                      :: SPSI (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_SPSI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VVEL (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: VVEL (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_VVEL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: URL (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: URL (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_URL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VRL (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: VRL (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_VRL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: WRL (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: WRL (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_WRL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: URL5 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: URL5 (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_URL5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VRL5 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: VRL5 (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_VRL5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: WRL5 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: WRL5 (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_WRL5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: USI5 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: USI5 (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_USI5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VSI5 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: VSI5 (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_VSI5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: U15 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: U15 (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_U15 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: V15 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: V15 (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_V15 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T15 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: T15 (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_T15 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: Q15 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: Q15 (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_Q15 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAPPA (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: KAPPA (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_KAPPA => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAPPAT (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: KAPPAT (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_KAPPAT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAPPAM (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: KAPPAM (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_KAPPAM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAPPAH (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: KAPPAH (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_KAPPAH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAPPA5 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: KAPPA5 (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_KAPPA5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAPPAT5 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: KAPPAT5 (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_KAPPAT5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWF (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: GWF (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_GWF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GDW (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: GDW (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_GDW => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWS (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: GWS (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_GWS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STDDISU (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: STDDISU (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_STDDISU => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STDDISV (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: STDDISV (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_STDDISV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STDDISW (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: STDDISW (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_STDDISW => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZRL (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: ZRL (NPROMA, 0:NLEV+1)
  CLASS (FIELD_3RB), POINTER :: F_ZRL => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_SL2_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_SL2_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_SL2_TYPE_FINAL
END TYPE CPG_SL2_TYPE

REAL(KIND=JPRB),    PRIVATE, SAVE, TARGET :: ZDUM1 (1), ZDUM2 (1, 1), ZDUM3 (1,1,1)
INTEGER(KIND=JPIM), PRIVATE, SAVE, TARGET :: IDUM1 (1), IDUM2 (1, 1), IDUM3 (1,1,1)

CONTAINS

SUBROUTINE CPG_XYBDER_TYPE_INIT (SELF, REGISTRY, NLEV, &
                        & YDTXYBDER, PERSISTENT, PTXYBDER)

USE INTDYN_MOD, ONLY : TXYBDER

CLASS (CPG_XYBDER_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TXYBDER),                    INTENT (IN)    :: YDTXYBDER
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTXYBDER (:, :, :, :)

LOGICAL :: LLPERSISTENT


















END SUBROUTINE CPG_XYBDER_TYPE_INIT

SUBROUTINE CPG_XYBDER_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_XYBDER_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX



END SUBROUTINE CPG_XYBDER_TYPE_UPDATE_VIEW

SUBROUTINE CPG_XYBDER_TYPE_FINAL (SELF)
CLASS (CPG_XYBDER_TYPE)          :: SELF



















END SUBROUTINE CPG_XYBDER_TYPE_FINAL

SUBROUTINE CPG_XYB_TYPE_INIT (SELF, REGISTRY, NLEV, &
                        & YDTXYB, PERSISTENT, PTXYB)

USE INTDYN_MOD, ONLY : TXYB

CLASS (CPG_XYB_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TXYB),                    INTENT (IN)    :: YDTXYB
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTXYB (:, :, :, :)

LOGICAL :: LLPERSISTENT
















END SUBROUTINE CPG_XYB_TYPE_INIT

SUBROUTINE CPG_XYB_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_XYB_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX



END SUBROUTINE CPG_XYB_TYPE_UPDATE_VIEW

SUBROUTINE CPG_XYB_TYPE_FINAL (SELF)
CLASS (CPG_XYB_TYPE)          :: SELF

















END SUBROUTINE CPG_XYB_TYPE_FINAL

SUBROUTINE CPG_HWIND_TYPE_INIT (SELF, REGISTRY, NLEV, &
                        & YDTHWIND, PERSISTENT, PTHWIND)

USE INTDYN_MOD, ONLY : THWIND

CLASS (CPG_HWIND_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (THWIND),                    INTENT (IN)    :: YDTHWIND
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTHWIND (:, :, :, :)

LOGICAL :: LLPERSISTENT












END SUBROUTINE CPG_HWIND_TYPE_INIT

SUBROUTINE CPG_HWIND_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_HWIND_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX



END SUBROUTINE CPG_HWIND_TYPE_UPDATE_VIEW

SUBROUTINE CPG_HWIND_TYPE_FINAL (SELF)
CLASS (CPG_HWIND_TYPE)          :: SELF













END SUBROUTINE CPG_HWIND_TYPE_FINAL

SUBROUTINE CPG_RCP_TYPE_INIT (SELF, REGISTRY, NLEV, &
                        & YDTRCP, PERSISTENT, PTRCP)

USE INTDYN_MOD, ONLY : TRCP

CLASS (CPG_RCP_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TRCP),                    INTENT (IN)    :: YDTRCP
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTRCP (:, :, :, :)

LOGICAL :: LLPERSISTENT












END SUBROUTINE CPG_RCP_TYPE_INIT

SUBROUTINE CPG_RCP_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_RCP_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX



END SUBROUTINE CPG_RCP_TYPE_UPDATE_VIEW

SUBROUTINE CPG_RCP_TYPE_FINAL (SELF)
CLASS (CPG_RCP_TYPE)          :: SELF













END SUBROUTINE CPG_RCP_TYPE_FINAL

SUBROUTINE CPG_CTY_TYPE_INIT (SELF, REGISTRY, NLEV, &
                        & YDTCTY, PERSISTENT, PTCTY)

USE INTDYN_MOD, ONLY : TCTY

CLASS (CPG_CTY_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TCTY),                    INTENT (IN)    :: YDTCTY
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTCTY (:, :, :, :)

LOGICAL :: LLPERSISTENT














END SUBROUTINE CPG_CTY_TYPE_INIT

SUBROUTINE CPG_CTY_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_CTY_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX



END SUBROUTINE CPG_CTY_TYPE_UPDATE_VIEW

SUBROUTINE CPG_CTY_TYPE_FINAL (SELF)
CLASS (CPG_CTY_TYPE)          :: SELF















END SUBROUTINE CPG_CTY_TYPE_FINAL

SUBROUTINE CPG_TND_TYPE_INIT (SELF, REGISTRY, NLEV, &
                        & YDTTND, PERSISTENT, PTTND)

USE INTDYN_MOD, ONLY : TTND

CLASS (CPG_TND_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TTND),                    INTENT (IN)    :: YDTTND
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTTND (:, :, :, :)

LOGICAL :: LLPERSISTENT

















END SUBROUTINE CPG_TND_TYPE_INIT

SUBROUTINE CPG_TND_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_TND_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX



END SUBROUTINE CPG_TND_TYPE_UPDATE_VIEW

SUBROUTINE CPG_TND_TYPE_FINAL (SELF)
CLASS (CPG_TND_TYPE)          :: SELF


















END SUBROUTINE CPG_TND_TYPE_FINAL

SUBROUTINE CPG_GPAR_TYPE_INIT (SELF, REGISTRY, YDCPG_OPTS, YDTPARAR, PERSISTENT, PTPARAR)

USE YOMPARAR, ONLY : TPARAR
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_OPTS_TYPE

CLASS (CPG_GPAR_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
TYPE (CPG_OPTS_TYPE),               INTENT (IN)    :: YDCPG_OPTS
TYPE (TPARAR),                    INTENT (IN)    :: YDTPARAR
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTPARAR (:, :, :)

LOGICAL :: LLPERSISTENT




























END SUBROUTINE CPG_GPAR_TYPE_INIT

SUBROUTINE CPG_GPAR_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_GPAR_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX



END SUBROUTINE CPG_GPAR_TYPE_UPDATE_VIEW

SUBROUTINE CPG_GPAR_TYPE_FINAL (SELF)
CLASS (CPG_GPAR_TYPE)          :: SELF





























END SUBROUTINE CPG_GPAR_TYPE_FINAL




SUBROUTINE CPG_DYN_TYPE_INIT (SELF &
                                & , KT  &
                                & , REGISTRY &
                                & , NLEV &
                                & , PERSISTENT &
                                & , YDDYNA &
                           &, PHIF &
                           &, PREF &
                           &, PRCP &
                           &, PCTY &
                           &)

USE INTDYN_MOD, ONLY : YYTCTY0, YYTRCP0, YYTHW0, YYTXYB0, YYTXYB0_PHY, YYTXYBDER0
USE INTDYN_MOD, ONLY :          YYTRCP9, YYTHW9, YYTXYB9, YYTXYB9_PHY
USE INTDYN_MOD, ONLY : TRCP, TCTY, THWIND, TXYB, TXYBDER


USE YOMDYNA, ONLY : TDYNA

CLASS (CPG_DYN_TYPE)                    :: SELF
INTEGER(KIND=JPIM),           INTENT (IN)    :: KT
TYPE (FIELD_REGISTRY),        INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),          INTENT (IN)    :: NLEV
LOGICAL, OPTIONAL,            INTENT (IN)    :: PERSISTENT
TYPE (TDYNA),                 INTENT (IN)    :: YDDYNA

REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PHIF(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PREF(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PRCP(:, :, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PCTY(:, :, :, :)

LOGICAL :: LLT0

TYPE (TRCP)   , POINTER :: YLTRCP     
TYPE (TCTY)   , POINTER :: YLTCTY     
TYPE (THWIND) , POINTER :: YLTHW     
TYPE (TXYB)   , POINTER :: YLTXYB     
TYPE (TXYB)   , POINTER :: YLTXYB_PHY
TYPE (TXYBDER), POINTER :: YLTXYBDER

TYPE (TCTY),   TARGET :: YLTCTY0 
TYPE (THWIND), TARGET :: YLTHW0, YLTHW9 
TYPE (TRCP),   TARGET :: YLTRCP0, YLTRCP9 
TYPE (TXYB),   TARGET :: YLTXYB0, YLTXYB0_PHY, YLTXYB9, YLTXYB9_PHY
TYPE (TXYBDER),TARGET :: YLTXYBDER0

 
 
 
 
 
 
 
 












































































END SUBROUTINE CPG_DYN_TYPE_INIT

SUBROUTINE CPG_DYN_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_DYN_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX
































END SUBROUTINE CPG_DYN_TYPE_UPDATE_VIEW

SUBROUTINE CPG_DYN_TYPE_FINAL (SELF)
CLASS (CPG_DYN_TYPE)         :: SELF

 
 
 
 
 
 
 
 
 
 




 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

END SUBROUTINE CPG_DYN_TYPE_FINAL




SUBROUTINE CPG_PHY_TYPE_INIT (SELF &
                                & , KT  &
                                & , REGISTRY &
                                & , NLEV &
                                & , PERSISTENT &
                                & , LDMF_PHYS &
                           &)

USE INTDYN_MOD, ONLY : YYTCTY0, YYTRCP0, YYTHW0, YYTXYB0, YYTXYB0_PHY, YYTXYBDER0
USE INTDYN_MOD, ONLY :          YYTRCP9, YYTHW9, YYTXYB9, YYTXYB9_PHY
USE INTDYN_MOD, ONLY : TRCP, TCTY, THWIND, TXYB, TXYBDER



CLASS (CPG_PHY_TYPE)                    :: SELF
INTEGER(KIND=JPIM),           INTENT (IN)    :: KT
TYPE (FIELD_REGISTRY),        INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),          INTENT (IN)    :: NLEV
LOGICAL, OPTIONAL,            INTENT (IN)    :: PERSISTENT
LOGICAL, OPTIONAL,            INTENT (IN)    :: LDMF_PHYS


LOGICAL :: LLT0
LOGICAL :: LLMF_PHYS

TYPE (TRCP)   , POINTER :: YLTRCP     
TYPE (TCTY)   , POINTER :: YLTCTY     
TYPE (THWIND) , POINTER :: YLTHW     
TYPE (TXYB)   , POINTER :: YLTXYB     
TYPE (TXYB)   , POINTER :: YLTXYB_PHY
TYPE (TXYBDER), POINTER :: YLTXYBDER

TYPE (TCTY),   TARGET :: YLTCTY0 
TYPE (THWIND), TARGET :: YLTHW0, YLTHW9 
TYPE (TRCP),   TARGET :: YLTRCP0, YLTRCP9 
TYPE (TXYB),   TARGET :: YLTXYB0, YLTXYB0_PHY, YLTXYB9, YLTXYB9_PHY
TYPE (TXYBDER),TARGET :: YLTXYBDER0

 
 
 
 
 
 
 
 


































END SUBROUTINE CPG_PHY_TYPE_INIT

SUBROUTINE CPG_PHY_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_PHY_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX










END SUBROUTINE CPG_PHY_TYPE_UPDATE_VIEW

SUBROUTINE CPG_PHY_TYPE_FINAL (SELF)
CLASS (CPG_PHY_TYPE)         :: SELF


 
 
 
 
 
 
 

END SUBROUTINE CPG_PHY_TYPE_FINAL




SUBROUTINE CPG_MISC_TYPE_INIT (SELF &
                                & , REGISTRY &
                                & , YDCPG_OPTS &
                                & , PERSISTENT &
                           &)


USE CPG_OPTS_TYPE_MOD, ONLY : CPG_OPTS_TYPE


CLASS (CPG_MISC_TYPE)                    :: SELF
TYPE (FIELD_REGISTRY),        INTENT (INOUT) :: REGISTRY
TYPE (CPG_OPTS_TYPE),         INTENT (IN)    :: YDCPG_OPTS
LOGICAL, OPTIONAL,            INTENT (IN)    :: PERSISTENT






































END SUBROUTINE CPG_MISC_TYPE_INIT

SUBROUTINE CPG_MISC_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_MISC_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

















END SUBROUTINE CPG_MISC_TYPE_UPDATE_VIEW

SUBROUTINE CPG_MISC_TYPE_FINAL (SELF)
CLASS (CPG_MISC_TYPE)         :: SELF

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

END SUBROUTINE CPG_MISC_TYPE_FINAL

SUBROUTINE CPG_DDH_TYPE_INIT (SELF, REGISTRY, NLEV, PERSISTENT, YDMODEL, YDDDH)

USE TYPE_MODEL, ONLY : MODEL
USE DDH_MIX, ONLY : TYP_DDH

CLASS (CPG_DDH_TYPE)                             :: SELF
TYPE (FIELD_REGISTRY),            INTENT (IN)    :: REGISTRY
INTEGER (KIND=JPIM),              INTENT (IN)    :: NLEV
LOGICAL, OPTIONAL,                INTENT (IN)    :: PERSISTENT
TYPE (MODEL),                     INTENT (IN)    :: YDMODEL
TYPE (TYP_DDH),                   INTENT (IN)    :: YDDDH




END SUBROUTINE CPG_DDH_TYPE_INIT

SUBROUTINE CPG_DDH_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_DDH_TYPE)              :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX







END SUBROUTINE CPG_DDH_TYPE_UPDATE_VIEW

SUBROUTINE CPG_DDH_TYPE_FINAL (SELF)

CLASS (CPG_DDH_TYPE)              :: SELF













END SUBROUTINE CPG_DDH_TYPE_FINAL




SUBROUTINE GREPVARS (YDCPG_SL1, YDMODEL, COND, YDVARS_LIST)
USE TYPE_MODEL, ONLY : MODEL
TYPE(CPG_SL1_TYPE), INTENT(INOUT) :: YDCPG_SL1
TYPE(MODEL), INTENT(IN) :: YDMODEL
PROCEDURE (FUN_GREP) :: COND
TYPE (CPG_SL1_3D_TYPE), ALLOCATABLE :: YDVARS_LIST (:)

INTEGER (KIND=JPIM) :: ISIZE, JFLD, IPNTR




































































































































    
END SUBROUTINE

SUBROUTINE CPG_SL1_TYPE_ZERO (SELF)

CLASS (CPG_SL1_TYPE) :: SELF

END SUBROUTINE

SUBROUTINE CPG_SL1_TYPE_INIT (SELF, REGISTRY, NLEV, YDTPTRSLB1 &
                                & , YDMODEL &
                                & , YGFL &
                                & , PERSISTENT, PB1)

USE PTRSLB1, ONLY : TPTRSLB1

USE YOM_YGFL, ONLY: TYPE_GFLD
USE TYPE_MODEL, ONLY : MODEL

CLASS (CPG_SL1_TYPE)                               :: SELF
TYPE (FIELD_REGISTRY),              INTENT (IN)    :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TPTRSLB1),                    INTENT (IN)    :: YDTPTRSLB1
TYPE (TYPE_GFLD),                   INTENT (IN)    :: YGFL
TYPE (MODEL),                       INTENT (IN)    :: YDMODEL
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PB1 (:, :, :)

INTEGER (KIND=JPIM) :: JFLD
INTEGER (KIND=JPIM) :: JGFL
INTEGER (KIND=JPIM) :: ISIZE, IPNTR
INTEGER (KIND=JPIM) :: ISIZE_1, IPNTR_1
INTEGER (KIND=JPIM) :: ISIZE_2, IPNTR_2

INTEGER (KIND=JPIM) :: ISLB1GFL9

LOGICAL :: LLPERSISTENT










  



















































































































































































































































END SUBROUTINE CPG_SL1_TYPE_INIT

SUBROUTINE CPG_SL1_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_SL1_TYPE)        :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

INTEGER (KIND=JPIM) :: JGFL











END SUBROUTINE CPG_SL1_TYPE_UPDATE_VIEW

SUBROUTINE CPG_SL1_TYPE_FINAL (SELF)
CLASS (CPG_SL1_TYPE)          :: SELF

INTEGER (KIND=JPIM) :: JGFL





















































































































































































































































































END SUBROUTINE CPG_SL1_TYPE_FINAL

SUBROUTINE CPG_SL2_TYPE_INIT (SELF, REGISTRY, NLEV, YDTPTRSLB2 &
                                & , PERSISTENT, PB2)

USE PTRSLB2, ONLY : TPTRSLB2

CLASS (CPG_SL2_TYPE)                               :: SELF
TYPE (FIELD_REGISTRY),              INTENT (IN)    :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TPTRSLB2),                    INTENT (IN)    :: YDTPTRSLB2
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PB2 (:, :, :)

INTEGER (KIND=JPIM) :: JFLD

LOGICAL :: LLPERSISTENT














































END SUBROUTINE CPG_SL2_TYPE_INIT

SUBROUTINE CPG_SL2_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_SL2_TYPE)        :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX



END SUBROUTINE CPG_SL2_TYPE_UPDATE_VIEW

SUBROUTINE CPG_SL2_TYPE_FINAL (SELF)
CLASS (CPG_SL2_TYPE)          :: SELF
















































































































END SUBROUTINE CPG_SL2_TYPE_FINAL

END MODULE CPG_TYPE_MOD

