MODULE FIELD_CONTAINER_BASE_MOD 
USE PARKIND1, ONLY: JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE FIELD_DEFINITIONS_BASE, ONLY: TYPE_FVAR,TYPE_CONTROL, &
  & FIELD_ACCESS_BASE, FIELD_METADATA_BASE
USE FIELD_DEFINITIONS,      ONLY: FIELD_ACCESS,FIELD_METADATA
USE FIELD_GFL_WRAPPER,      ONLY: TGFL_MAP_INTERNAL
IMPLICIT NONE

PRIVATE

INTEGER(KIND=JPIM), PUBLIC,PARAMETER :: JP_STORAGE1D  = 1 ! basic 1d storage scheme (not rank-conformant at f95)
INTEGER(KIND=JPIM), PUBLIC,PARAMETER :: JP_STORAGE_ARR  = 2 ! "3d" storage scheme preserving rank-conformance
INTEGER(KIND=JPIM), PUBLIC,PARAMETER :: JP_STORAGEOLD = 3 ! backward compatibility: use old gfl, gmvs etc.
TYPE ,PUBLIC :: TYPE_FIELD_INDEX_BASE
  LOGICAL :: L_ON = .FALSE.     ! Requested but possibly pointing to "NUNDEF" in old storage
  LOGICAL :: L_ACTIVE = .FALSE. ! Allocated "active" field
END TYPE TYPE_FIELD_INDEX_BASE
TYPE TYPE_STORAGE_ARRAYS
  REAL(KIND=JPRB),ALLOCATABLE :: STORE1D(:)
  REAL(KIND=JPRB),ALLOCATABLE :: STORE2D(:,:)
  REAL(KIND=JPRB),ALLOCATABLE :: STORE3D(:,:,:)
  REAL(KIND=JPRB),ALLOCATABLE :: STORE4D(:,:,:,:)
END type TYPE_STORAGE_ARRAYS
TYPE, PUBLIC :: TYPE_ITERATOR
INTEGER(KIND=JPIM) :: ICURRENT=0
END type TYPE_ITERATOR

TYPE,PUBLIC :: FIELD_CONTAINER_BASE
!  PRIVATE
  LOGICAL            :: LCREATED=.FALSE.
  INTEGER(KIND=JPIM) :: MSTORTYPE 
  INTEGER(KIND=JPIM) :: M_ATTACH ! If attached to GFLs, what time level?
  INTEGER(KIND=JPIM) :: NFIELDS
  INTEGER(KIND=JPIM) :: NFIELDS_ON
  INTEGER(KIND=JPIM), ALLOCATABLE :: MALL_FIELDS(:)
  TYPE(TYPE_FIELD_INDEX_BASE),ALLOCATABLE:: FIELD_INDEX(:)
  TYPE(TYPE_STORAGE_ARRAYS), ALLOCATABLE       :: STORAGE_ARRAYS(:)
  INTEGER(KIND=JPIM),PRIVATE          :: NLEVELTYPES=0
  INTEGER(KIND=JPIM),PRIVATE          :: NDIM3TYPES=0
  TYPE(TYPE_FVAR), ALLOCATABLE    :: METADATA(:) !=> NULL()
  TYPE(TGFL_MAP_INTERNAL)     :: GFL_MAP_INTERNAL
  INTEGER(KIND=JPIM)          :: NPOINTS
  INTEGER(KIND=JPIM), ALLOCATABLE:: NLEVELS(:)  ! Number of levels (there will usually be several options)
  INTEGER(KIND=JPIM), ALLOCATABLE:: NDIM3S(:)  ! Third dimesions (there will usually be several options)
  CHARACTER(LEN=3), ALLOCATABLE:: CLEVTYPE(:)  ! IFS level type (SFC or ML) of each field-container level type
  CONTAINS
  PROCEDURE :: FIELD_ACTIVE_CONTAINER
  PROCEDURE :: FIELD_CREATE_BASE
  PROCEDURE :: SETUP_ACTIVE_FIELDS
  PROCEDURE :: ALLOCATE_STORAGE_ARRAYS
  PROCEDURE :: DEALLOCATE_STORAGE_ARRAYS
  PROCEDURE :: GET_STORE_TYPE
  PROCEDURE :: GET_USED_FIELDS
  PROCEDURE :: GET_ACTIVE_FIELDS
END TYPE FIELD_CONTAINER_BASE
CONTAINS
!=======================================================================================
FUNCTION FIELD_ACTIVE_CONTAINER(SELF,KFID)





CLASS(FIELD_CONTAINER_BASE), INTENT(IN) :: SELF
INTEGER(KIND=JPIM),    INTENT(IN) :: KFID
LOGICAL :: FIELD_ACTIVE_CONTAINER
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE





END FUNCTION FIELD_ACTIVE_CONTAINER
!=======================================================================================
SUBROUTINE FIELD_CREATE_BASE(SELF,NAMESPACE,KPOINTS,KLEVELS,KFIDS,KATTACH,KSTORAGE_TYPE,KDIM3S)
CLASS(FIELD_CONTAINER_BASE), INTENT(INOUT) :: SELF
CLASS(FIELD_METADATA_BASE),   INTENT(IN)    :: NAMESPACE  
INTEGER(KIND=JPIM),           INTENT(IN)    :: KPOINTS    
INTEGER(KIND=JPIM),           INTENT(IN)    :: KLEVELS(:) 
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: KFIDS(:)    
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: KATTACH     
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: KSTORAGE_TYPE
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: KDIM3S(:)
INTEGER(KIND=JPIM) :: JLEVELTYPE
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
























END SUBROUTINE FIELD_CREATE_BASE
!=======================================================================================
SUBROUTINE SETUP_ACTIVE_FIELDS(SELF,KFIDS)
CLASS(FIELD_CONTAINER_BASE), INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: KFIDS(:)    

INTEGER(KIND=JPIM) :: I,ID
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE







END SUBROUTINE SETUP_ACTIVE_FIELDS
!=======================================================================================
SUBROUTINE ALLOCATE_STORAGE_ARRAYS(SELF,KPROMA)
CLASS(FIELD_CONTAINER_BASE), INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) :: ITOTLEVS,ID,INLEVELS,IBLOCKS,INDIM3
LOGICAL :: LLNPROMA
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE ALLOCATE_STORAGE_ARRAYS
!=======================================================================================
SUBROUTINE DEALLOCATE_STORAGE_ARRAYS(SELF)
CLASS(FIELD_CONTAINER_BASE), INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM) :: ID
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE






END SUBROUTINE DEALLOCATE_STORAGE_ARRAYS
!=======================================================================================
FUNCTION GET_STORE_TYPE(SELF)
CLASS(FIELD_CONTAINER_BASE), INTENT(IN) :: SELF
INTEGER(KIND=JPIM) :: GET_STORE_TYPE
REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE


END FUNCTION GET_STORE_TYPE

!=======================================================================================
SUBROUTINE GET_USED_FIELDS(SELF,KUSED_FIELDS,KFIDS)
CLASS(FIELD_CONTAINER_BASE), INTENT(IN) :: SELF
INTEGER(KIND=JPIM),ALLOCATABLE,INTENT(OUT) :: KUSED_FIELDS(:)
INTEGER(KIND=JPIM), TARGET, OPTIONAL,INTENT(IN) :: KFIDS(:) 
INTEGER(KIND=JPIM) :: IFIELDS_USED,ID,J,IUSED_FIDS(SELF%NFIELDS)
LOGICAL :: LLON
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE GET_USED_FIELDS
!=======================================================================================

SUBROUTINE GET_ACTIVE_FIELDS(SELF,KACTIVE_FIELDS,KFIDS)
CLASS(FIELD_CONTAINER_BASE), INTENT(IN) :: SELF
INTEGER(KIND=JPIM),ALLOCATABLE,INTENT(OUT) :: KACTIVE_FIELDS(:)
INTEGER(KIND=JPIM), TARGET, OPTIONAL,INTENT(IN) :: KFIDS(:) 
INTEGER(KIND=JPIM) :: IFIELDS_ACTIVE,ID,J,IACTIVE_FIDS(SELF%NFIELDS)
LOGICAL :: LLACTIVE
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE GET_ACTIVE_FIELDS

!=======================================================================================
END MODULE FIELD_CONTAINER_BASE_MOD
