MODULE FIELD_4LM_MODULE


USE FIELD_BASIC_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

INTEGER (KIND=JPIM), PARAMETER :: NDEVFRESH = INT(B'00000001', KIND=JPIM)
INTEGER (KIND=JPIM), PARAMETER :: NHSTFRESH = INT(B'00000010', KIND=JPIM)
INTEGER (KIND=JPIM), PARAMETER :: UNALLOCATED = INT(B'00000100', KIND=JPIM)
INTEGER (KIND=JPIM), PARAMETER :: NH2D = 1, ND2H = 2
INTEGER (KIND=JPIM), PARAMETER :: NRD = INT(B'00000001', KIND=JPIM)
INTEGER (KIND=JPIM), PARAMETER :: NWR = INT(B'00000010', KIND=JPIM)

TYPE, ABSTRACT, EXTENDS (FIELD_BASIC) :: FIELD_4LM
  LOGICAL(KIND=JPLM), POINTER :: PTR(:,:,:,:) => NULL()
  LOGICAL(KIND=JPLM), POINTER, CONTIGUOUS :: DEVPTR(:,:,:,:) => NULL()
CONTAINS

  PROCEDURE :: FINAL => FIELD_4LM_FINAL
  PROCEDURE :: FIELD_4LM_FINAL
  PROCEDURE :: DELETE_DEVICE => FIELD_4LM_DELETE_DEVICE
  PROCEDURE :: GET_VIEW => FIELD_4LM_GET_VIEW
  PROCEDURE :: GET_DEVICE_DATA_RDONLY => FIELD_4LM_GET_DEVICE_DATA_RDONLY
  PROCEDURE :: GET_DEVICE_DATA_RDWR => FIELD_4LM_GET_DEVICE_DATA_RDWR
  PROCEDURE :: GET_HOST_DATA_RDONLY => FIELD_4LM_GET_HOST_DATA_RDONLY
  PROCEDURE :: GET_HOST_DATA_RDWR => FIELD_4LM_GET_HOST_DATA_RDWR
  PROCEDURE :: SYNC_HOST_RDWR => FIELD_4LM_SYNC_HOST_RDWR
  PROCEDURE :: SYNC_HOST_RDONLY => FIELD_4LM_SYNC_HOST_RDONLY
  PROCEDURE :: SYNC_DEVICE_RDWR => FIELD_4LM_SYNC_DEVICE_RDWR
  PROCEDURE :: SYNC_DEVICE_RDONLY => FIELD_4LM_SYNC_DEVICE_RDONLY
  PROCEDURE :: COPY_OBJECT => FIELD_4LM_COPY_OBJECT
  PROCEDURE :: WIPE_OBJECT => FIELD_4LM_WIPE_OBJECT

  PROCEDURE, PRIVATE :: GET_DEVICE_DATA => FIELD_4LM_GET_DEVICE_DATA
  PROCEDURE, PRIVATE :: GET_HOST_DATA => FIELD_4LM_GET_HOST_DATA
  PROCEDURE, PRIVATE :: FIELD_4LM_GET_HOST_DATA
  PROCEDURE, PRIVATE :: COPY_DATA =>  FIELD_4LM_COPY_DATA
  PROCEDURE, PRIVATE :: CREATE_DEVICE_DATA => FIELD_4LM_CREATE_DEVICE_DATA
END TYPE FIELD_4LM

PUBLIC :: FIELD_4LM

TYPE, EXTENDS(FIELD_4LM) :: FIELD_4LM_WRAPPER
CONTAINS
  PROCEDURE :: INIT => FIELD_4LM_WRAP
  PROCEDURE :: FINAL => FIELD_4LM_WRAPPER_FINAL
END TYPE FIELD_4LM_WRAPPER

PUBLIC :: FIELD_4LM_WRAPPER

TYPE, EXTENDS(FIELD_4LM) :: FIELD_4LM_OWNER
  INTEGER(KIND=JPIM) :: LBOUNDS(4), UBOUNDS(4)
CONTAINS
  PROCEDURE :: INIT => FIELD_4LM_OWNER_INIT
  PROCEDURE :: FINAL => FIELD_4LM_OWNER_FINAL
  PROCEDURE, PRIVATE :: ALLOCATE => FIELD_4LM_ALLOCATE
  PROCEDURE, PRIVATE :: GET_HOST_DATA => FIELD_4LM_OWNER_GET_HOST_DATA
END TYPE FIELD_4LM_OWNER

PUBLIC :: FIELD_4LM_OWNER

TYPE FIELD_4LM_PTR
  CLASS(FIELD_4LM), POINTER :: PTR => NULL()
END TYPE FIELD_4LM_PTR

PUBLIC :: FIELD_4LM_PTR

TYPE FIELD_4LM_VIEW
  LOGICAL(KIND=JPLM), POINTER :: P(:,:,:) => NULL()
END TYPE FIELD_4LM_VIEW

PUBLIC :: FIELD_4LM_VIEW


CONTAINS

  SUBROUTINE FIELD_4LM_WRAP(SELF, DATA, PERSISTENT, LBOUNDS)
    
    CLASS(FIELD_4LM_WRAPPER), INTENT(INOUT) :: SELF
    LOGICAL(KIND=JPLM), TARGET, INTENT(IN) :: DATA(:,:,:,:)
    LOGICAL, INTENT(IN), OPTIONAL :: PERSISTENT
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(4)
    LOGICAL :: LLPERSISTENT

    
    

    
    
    

    

  END SUBROUTINE FIELD_4LM_WRAP

  SUBROUTINE FIELD_4LM_OWNER_INIT (SELF, LBOUNDS, UBOUNDS, PERSISTENT, DELAYED)
    CLASS(FIELD_4LM_OWNER) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(4)
    INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
    LOGICAL, OPTIONAL,  INTENT(IN) :: PERSISTENT
    LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
    LOGICAL :: IS_DELAYED

    
    

    
    
    

    
    

    

    

    
    
  END SUBROUTINE FIELD_4LM_OWNER_INIT

  SUBROUTINE FIELD_4LM_ALLOCATE (SELF)
    
    CLASS(FIELD_4LM_OWNER) :: SELF

    
    
  END SUBROUTINE FIELD_4LM_ALLOCATE

  FUNCTION FIELD_4LM_GET_VIEW(SELF, BLOCK_INDEX, ZERO) RESULT(VIEW_PTR)
    CLASS(FIELD_4LM) :: SELF
    LOGICAL(KIND=JPLM), POINTER :: VIEW_PTR(:,:,:)
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    LOGICAL, OPTIONAL,  INTENT(IN) :: ZERO
    INTEGER(KIND=JPIM) :: IDX
    INTEGER(KIND=JPIM) :: LBOUNDS(4)

    
    

    
    

    
  END FUNCTION FIELD_4LM_GET_VIEW

  SUBROUTINE FIELD_4LM_DELETE_DEVICE(SELF)
    
    CLASS(FIELD_4LM) :: SELF

    
  END SUBROUTINE FIELD_4LM_DELETE_DEVICE

  SUBROUTINE FIELD_4LM_FINAL(SELF)
    
    CLASS(FIELD_4LM) :: SELF
    
    
  END SUBROUTINE FIELD_4LM_FINAL

  SUBROUTINE FIELD_4LM_WRAPPER_FINAL(SELF)
    
    CLASS(FIELD_4LM_WRAPPER) :: SELF
    LOGICAL(KIND=JPLM), POINTER :: PTR(:,:,:,:)
    
    
  END SUBROUTINE FIELD_4LM_WRAPPER_FINAL

  SUBROUTINE FIELD_4LM_OWNER_FINAL(SELF)
    
    CLASS(FIELD_4LM_OWNER) :: SELF
    
    
  END SUBROUTINE FIELD_4LM_OWNER_FINAL

  SUBROUTINE FIELD_4LM_COPY_OBJECT (SELF, LDCREATED)
  CLASS(FIELD_4LM) :: SELF
  LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED
  LOGICAL :: LLCREATED

  
  

  

  

  END SUBROUTINE FIELD_4LM_COPY_OBJECT

  SUBROUTINE FIELD_4LM_WIPE_OBJECT (SELF, LDDELETED)
  CLASS(FIELD_4LM) :: SELF
  LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED
  LOGICAL :: LLDELETED

  
  

  

  

  END SUBROUTINE FIELD_4LM_WIPE_OBJECT

  SUBROUTINE FIELD_4LM_COPY_DATA (SELF, KDIR, QUEUE)
  CLASS(FIELD_4LM) :: SELF
  INTEGER (KIND=JPIM),           INTENT(IN) :: KDIR
  INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN) :: QUEUE
  REAL :: START, FINISH

  

  
  
  
  

  

    

    

    

    

    


  END SUBROUTINE FIELD_4LM_COPY_DATA


  SUBROUTINE FIELD_4LM_GET_HOST_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_4LM),                INTENT(INOUT) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE

    LOGICAL(KIND=JPLM), POINTER,          INTENT(INOUT) :: PTR(:,:,:,:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

    INTEGER(KIND=JPIM) :: LBOUNDS(4)

    
    
    
    

  END SUBROUTINE FIELD_4LM_GET_HOST_DATA

  SUBROUTINE FIELD_4LM_OWNER_GET_HOST_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_4LM_OWNER),          INTENT(INOUT) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    LOGICAL(KIND=JPLM), POINTER,          INTENT(INOUT) :: PTR(:,:,:,:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

    
    

  END SUBROUTINE FIELD_4LM_OWNER_GET_HOST_DATA

  SUBROUTINE FIELD_4LM_GET_HOST_DATA_RDONLY (SELF, PPTR, QUEUE)
    CLASS(FIELD_4LM),               INTENT(INOUT) :: SELF
    LOGICAL(KIND=JPLM), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

    

  END SUBROUTINE FIELD_4LM_GET_HOST_DATA_RDONLY

  SUBROUTINE FIELD_4LM_SYNC_HOST_RDONLY (SELF, QUEUE)
    CLASS(FIELD_4LM),               INTENT(INOUT) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    LOGICAL(KIND=JPLM), POINTER                        :: ZPTR(:,:,:,:)

    

  END SUBROUTINE FIELD_4LM_SYNC_HOST_RDONLY

  SUBROUTINE FIELD_4LM_GET_HOST_DATA_RDWR (SELF, PPTR, QUEUE)
    CLASS(FIELD_4LM),   INTENT(INOUT) :: SELF
    LOGICAL(KIND=JPLM), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

    

  END SUBROUTINE FIELD_4LM_GET_HOST_DATA_RDWR

  SUBROUTINE FIELD_4LM_SYNC_HOST_RDWR (SELF, QUEUE)
    CLASS(FIELD_4LM),               INTENT(INOUT) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    LOGICAL(KIND=JPLM), POINTER                        :: ZPTR(:,:,:,:)

    

  END SUBROUTINE FIELD_4LM_SYNC_HOST_RDWR

  SUBROUTINE FIELD_4LM_CREATE_DEVICE_DATA (SELF)
    CLASS(FIELD_4LM), INTENT (INOUT) :: SELF
    
  END SUBROUTINE

  SUBROUTINE FIELD_4LM_GET_DEVICE_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_4LM),                INTENT(INOUT) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    LOGICAL(KIND=JPLM), POINTER,          INTENT(INOUT) :: PTR(:,:,:,:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    INTEGER(KIND=JPIM)                           :: LBOUNDS(4)

    
    
    
    

  END SUBROUTINE FIELD_4LM_GET_DEVICE_DATA

  SUBROUTINE FIELD_4LM_GET_DEVICE_DATA_RDONLY (SELF, PPTR, QUEUE)
    CLASS(FIELD_4LM),               INTENT(INOUT) :: SELF
    LOGICAL(KIND=JPLM), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

    

  END SUBROUTINE FIELD_4LM_GET_DEVICE_DATA_RDONLY

  SUBROUTINE FIELD_4LM_SYNC_DEVICE_RDONLY (SELF, QUEUE)
    CLASS(FIELD_4LM),               INTENT(INOUT) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    LOGICAL(KIND=JPLM), POINTER                        :: ZPTR(:,:,:,:)

    

  END SUBROUTINE FIELD_4LM_SYNC_DEVICE_RDONLY

  SUBROUTINE FIELD_4LM_GET_DEVICE_DATA_RDWR (SELF, PPTR, QUEUE)
    CLASS(FIELD_4LM),               INTENT(INOUT) :: SELF
    LOGICAL(KIND=JPLM), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

    

  END SUBROUTINE FIELD_4LM_GET_DEVICE_DATA_RDWR

  SUBROUTINE FIELD_4LM_SYNC_DEVICE_RDWR (SELF, QUEUE)
    CLASS(FIELD_4LM),               INTENT(INOUT) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    LOGICAL(KIND=JPLM), POINTER                        :: ZPTR(:,:,:,:)

    

  END SUBROUTINE FIELD_4LM_SYNC_DEVICE_RDWR


  INTEGER (KIND=JPIM) FUNCTION FIELD_4LM_GET_LAST_CONTIGUOUS_DIMENSION (PTR) RESULT (JDIM)
  LOGICAL(KIND=JPLM), POINTER :: PTR (:,:,:,:)
  INTEGER*8 :: ISTRIDE (4)
  INTEGER (KIND=JPIM) :: J, LB(4)

  
  
  

  
  

  

  

  

  

  

  

  

  END FUNCTION FIELD_4LM_GET_LAST_CONTIGUOUS_DIMENSION

END MODULE FIELD_4LM_MODULE
