MODULE FIELDS_BASE_MOD
USE PARKIND1,                        ONLY : JPRB, JPIM
USE YOMCT0,                          ONLY : LELAM
USE GEOMETRY_MOD,                    ONLY : GEOMETRY,GEOMETRY_SAME
USE TYPE_MODEL,                      ONLY : MODEL
USE FIELD_CONTAINER_GP_MOD,          ONLY : FIELD_CONTAINER_GP
USE VARIABLES_MOD,                   ONLY : VARIABLES, VARIABLES_CLONE, VARIABLES_DELETE
USE YOMMP0,                          ONLY : NPROC
USE FIELD_DEFINITIONS,               ONLY : FIELD_ACCESS,FID
USE YOMGRIB,                         ONLY : NLOCGRB

USE YOMHOOK,                         ONLY : LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE
PRIVATE
TYPE, PUBLIC :: FIELDS_BASE
  TYPE(VARIABLES)                   :: VARS
  TYPE(FIELD_CONTAINER_GP)          :: FIELDSTORE
  TYPE(GEOMETRY),           POINTER :: GEOM        => NULL()
  TYPE(MODEL),              POINTER :: STATE_MODEL => NULL()
  TYPE(FIELD_CONTAINER_GP), POINTER :: FIELD       => NULL()
  CONTAINS
  PROCEDURE :: FIELDS_CREATE
  PROCEDURE :: FIELDS_DELETE
  PROCEDURE :: FIELDS_ZEROS
  PROCEDURE :: FIELDS_COPY
  PROCEDURE :: FIELDS_SET_MODEL
  PROCEDURE :: FIELDS_AXPY
  PROCEDURE :: FIELDS_ADD
  PROCEDURE :: FIELDS_SUB
  PROCEDURE :: FIELDS_MUL
  PROCEDURE :: FIELDS_DOT_PROD
  PROCEDURE :: FIELDS_SCHUR_PROD
  PROCEDURE :: FIELDS_ADD_INCR
  PROCEDURE :: FIELDS_DIFF_INCR
  PROCEDURE :: FIELDS_NORM
  PROCEDURE :: FIELDS_L2_NORM
  PROCEDURE :: FIELDS_GPNORM
  PROCEDURE :: FIELDS_WRITE
  PROCEDURE :: FIELDS_READ
  PROCEDURE :: FIELDS_RANDOM
  PROCEDURE :: FIELDS_PGPSP
  FINAL :: FIELDS_BASE_FINAL
END TYPE FIELDS_BASE

PUBLIC INTREST,SPLIT_SPEC_GP
CONTAINS
!==========================================================================================

SUBROUTINE FIELDS_CREATE(SELF, GEOM, VARS)
USE FIELD_DEFINITIONS, ONLY : FID,MAIN_FIELD_METADATA
CLASS(FIELDS_BASE), TARGET, INTENT(INOUT) :: SELF
TYPE(GEOMETRY),     TARGET, INTENT(IN)    :: GEOM
TYPE(VARIABLES),            INTENT(IN)    :: VARS
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE















END SUBROUTINE FIELDS_CREATE
!==========================================================================================

SUBROUTINE FIELDS_DELETE(SELF)
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE FIELDS_DELETE
!==========================================================================================

SUBROUTINE FIELDS_ZEROS(SELF)
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM) :: JBLK
TYPE(FIELD_ACCESS)  :: YLFAC
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE




END SUBROUTINE FIELDS_ZEROS
!==========================================================================================

SUBROUTINE FIELDS_MUL(SELF,PZ)
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
REAL(KIND=JPRB),          INTENT(IN)    :: PZ
INTEGER(KIND=JPIM) :: JBLK,IST,IEND,IKGLO
TYPE(FIELD_ACCESS)  :: YLFAC
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE




END SUBROUTINE FIELDS_MUL
!==========================================================================================

SUBROUTINE FIELDS_COPY(SELF,RHS,KFIDS)
USE FIELD_DEFINITIONS, ONLY : FID,MAIN_FIELD_METADATA
USE YOMCT0, ONLY : NINTERPINCR
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
CLASS(FIELDS_BASE),TARGET,INTENT(INOUT) :: RHS
INTEGER(KIND=JPIM),OPTIONAL,TARGET,INTENT(IN) :: KFIDS(:)
TYPE(FIELD_ACCESS),POINTER  :: YLFAC,YLRHS
INTEGER(KIND=JPIM) :: JBLK
INTEGER(KIND=JPIM),POINTER :: IFIDS(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IFIDS_GP(:),IFIDS_SPEC(:)
REAL(KIND=JPRB),ALLOCATABLE    :: ZGPSPGLO(:,:)
TYPE(FIELDS_BASE),TARGET       :: RHS_SELFRES
TYPE(FIELDS_BASE),POINTER      :: RHS_SELFRES_PTR
LOGICAL :: LLSAME_RESOL,LLSPEC_INT
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE


















END SUBROUTINE FIELDS_COPY
!==========================================================================================

SUBROUTINE FIELDS_SET_MODEL(SELF,YDMODEL)
CLASS(FIELDS_BASE),         INTENT(INOUT) :: SELF
TYPE(MODEL)       , TARGET, INTENT(IN)    :: YDMODEL




END SUBROUTINE FIELDS_SET_MODEL
!==========================================================================================

SUBROUTINE FIELDS_AXPY(SELF,PZ,RHS,KFIDS,KFIDS_POSITIVE,LDSPEC_INT)
USE FIELD_DEFINITIONS, ONLY : FID,MAIN_FIELD_METADATA
USE YOMCT0, ONLY : NINTERPINCR
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
CLASS(FIELDS_BASE),TARGET,INTENT(INOUT) :: RHS
REAL(KIND=JPRB),          INTENT(IN)    :: PZ
INTEGER(KIND=JPIM),OPTIONAL,TARGET,INTENT(IN) :: KFIDS(:)
INTEGER(KIND=JPIM),OPTIONAL,TARGET,INTENT(IN) :: KFIDS_POSITIVE(:)
LOGICAL,OPTIONAL,INTENT(IN) :: LDSPEC_INT

INTEGER(KIND=JPIM) :: JBLK,IST,IEND,IKGLO
TYPE(FIELD_ACCESS), POINTER  :: YLFAC,YLRHS
INTEGER(KIND=JPIM),POINTER :: IFIDS(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IFIDS_GP(:),IFIDS_SPEC(:)
REAL(KIND=JPRB),ALLOCATABLE :: ZGPSPGLO(:,:)
TYPE(FIELDS_BASE),TARGET    :: RHS_SELFRES
TYPE(FIELDS_BASE),POINTER   :: RHS_SELFRES_PTR
LOGICAL :: LLSAME_RESOL,LLSPEC_INT
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE





END SUBROUTINE FIELDS_AXPY
!==========================================================================================

SUBROUTINE FIELDS_ADD(SELF,RHS)
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
CLASS(FIELDS_BASE),       INTENT(INOUT) :: RHS
integer(kind=jpim),save :: invocation=0
character(len=32) :: clfname
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE





END SUBROUTINE FIELDS_ADD
!==========================================================================================

SUBROUTINE FIELDS_SUB(SELF,RHS,KFIDS)
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
CLASS(FIELDS_BASE),       INTENT(INOUT) :: RHS
INTEGER(KIND=JPIM),OPTIONAL,TARGET,INTENT(IN) :: KFIDS(:)
INTEGER(KIND=JPIM),POINTER :: IFIDS(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE







END SUBROUTINE FIELDS_SUB
!==========================================================================================

SUBROUTINE FIELDS_DOT_PROD(SELF,RHS,PDOTP)
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
CLASS(FIELDS_BASE),       INTENT(INOUT) :: RHS
REAL(KIND=JPRB),          INTENT(OUT)   :: PDOTP
TYPE(FIELD_ACCESS)  :: YLFAC,YLRHS
REAL(KIND=JPRB) :: ZZ(1)
INTEGER(KIND=JPIM) :: JCOL,JBLK,ITID,IST,IEND,IBL,JL,IKGLO
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE




END SUBROUTINE FIELDS_DOT_PROD
!========================================================================================

SUBROUTINE FIELDS_L2_NORM(SELF,PDOTP)
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
REAL(KIND=JPRB),          INTENT(OUT)   :: PDOTP
TYPE(FIELD_ACCESS)  :: YLFAC
REAL(KIND=JPRB) :: ZZ(1)
INTEGER(KIND=JPIM) :: JCOL,JBLK,ITID,IST,IEND,IBL,JL,IKGLO
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE




END SUBROUTINE FIELDS_L2_NORM
!========================================================================================

SUBROUTINE FIELDS_NORM(SELF,CDGREP,PNORM,KFIDS)
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
CHARACTER(LEN=*),         INTENT(IN)    :: CDGREP
REAL(KIND=JPRB),          INTENT(OUT)   :: PNORM
INTEGER(KIND=JPIM),OPTIONAL,TARGET,INTENT(IN) :: KFIDS(:)

TYPE(FIELD_ACCESS)  :: YLFAC
REAL(KIND=JPRB) :: ZZ(1),ZMAXVAL_SELF,ZMINVAL_SELF
INTEGER(KIND=JPIM) :: JCOL,JBLK,IKGLO,IST,IEND
INTEGER(KIND=JPIM),POINTER :: IFIDS(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE





END SUBROUTINE FIELDS_NORM
!==========================================================================================

SUBROUTINE FIELDS_GPNORM(SELF,CDGREP,KFIDS,PMAX,PMIN)
CLASS(FIELDS_BASE),      INTENT(INOUT) :: SELF
CHARACTER(LEN=*),        INTENT(IN)    :: CDGREP
INTEGER(KIND=JPIM),OPTIONAL,TARGET,INTENT(IN) :: KFIDS(:)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT)   :: PMAX
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT)   :: PMIN

TYPE(FIELD_ACCESS)  :: YLFAC
REAL(KIND=JPRB) :: ZZ(1),ZMAXVAL_SELF,ZMINVAL_SELF
REAL(KIND=JPRB),ALLOCATABLE :: ZMEAN(:),ZMIN(:),ZMAX(:),ZGP(:,:,:),ZZMIN(:,:),ZZMAX(:,:)
REAL(KIND=JPRB),POINTER :: ZFIELD1(:),ZFIELD2(:,:)
INTEGER(KIND=JPIM) :: JCOL,JBLK,IKGLO,IST,IEND,IFIELDS,JFLD,ID,JL,JF,ITH,ITHMAX,IGPNMASTER,ITAG
INTEGER(KIND=JPIM),POINTER :: IFIDS(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE FIELDS_GPNORM
!==========================================================================================

SUBROUTINE FIELDS_SCHUR_PROD(SELF,RHS)
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
CLASS(FIELDS_BASE),       INTENT(INOUT) :: RHS
TYPE(FIELD_ACCESS), POINTER :: YLFAC,YLRHS
INTEGER(KIND=JPIM) :: JCOL,JBLK,ITID,IST,IEND,IBL,JL,IKGLO
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE






END SUBROUTINE FIELDS_SCHUR_PROD
!==========================================================================================

SUBROUTINE FIELDS_ADD_INCR(SELF,RHS)
USE FIELD_DEFINITIONS, ONLY : FID,MAIN_FIELD_METADATA,TYPE_FIELD_ID
USE YOMCT0, ONLY : NINTERPINCR

CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
CLASS(FIELDS_BASE),TARGET,INTENT(INOUT) :: RHS
REAL(KIND=JPRB) :: ZZ,ZEPS
TYPE(FIELDS_BASE),TARGET   :: RHS_SELFRES
TYPE(FIELDS_BASE),POINTER  :: RHS_SELFRES_PTR
LOGICAL :: LLSAME_RESOL
INTEGER(KIND=JPIM),POINTER :: IFIDS(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IFIDS_SPEC(:)
INTEGER(KIND=JPIM) :: IFIDS_POSITIVE(1)
INTEGER(KIND=JPIM),ALLOCATABLE :: IFIDS_GP(:)
REAL(KIND=JPRB), ALLOCATABLE :: ZGPSPGLO(:,:)
TYPE(FIELD_ACCESS) :: YLFAC,YLRHS
TYPE(TYPE_FIELD_ID) :: YLFID
INTEGER(KIND=JPIM) :: JBLK,IST,IEND,IKGLO
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE




































END SUBROUTINE FIELDS_ADD_INCR
!==========================================================================================

SUBROUTINE FIELDS_DIFF_INCR(SELF,X1,X2)
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
CLASS(FIELDS_BASE),       INTENT(INOUT) :: X1
CLASS(FIELDS_BASE),       INTENT(INOUT) :: X2

INTEGER(KIND=JPIM),POINTER :: IFIDS(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE












END SUBROUTINE FIELDS_DIFF_INCR
!==========================================================================================

SUBROUTINE FIELDS_WRITE(SELF,CDFNAME,KFIDS,LDWRITE_SPEC)
USE FIELD_DEFINITIONS     , ONLY : FID, MAIN_FIELD_METADATA
USE FIELD_CONTAINER_SP_MOD, ONLY : FIELD_CONTAINER_SP,TYPE_ITERATOR
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
CHARACTER(LEN=*), OPTIONAL, INTENT(IN)  :: CDFNAME
INTEGER(KIND=JPIM),OPTIONAL,TARGET,INTENT(IN) :: KFIDS(:)
LOGICAL,OPTIONAL,INTENT(IN) :: LDWRITE_SPEC

INTEGER(KIND=JPIM),POINTER :: IFIDS(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IFIDS_GP(:),IFIDS_SPEC(:),IFIDS_GP_REMOVE(:)
INTEGER(KIND=JPIM) :: JFLD,IFIELDS_GP,JF,IST,IEND,ID,IKGLO,JBLK,INLEVS
INTEGER(KIND=JPIM) :: IOPROC,ILOCGRB
INTEGER(KIND=JPIM) :: ILEVS(SELF%GEOM%YRDIMV%NFLEVG),IBSETS(SELF%GEOM%YRDIMV%NFLEVG)
INTEGER(KIND=JPIM) :: JL,IGRIBS(SELF%GEOM%YRDIMV%NFLEVG)
INTEGER(KIND=JPIM),ALLOCATABLE,TARGET :: IACTIVE(:)
REAL(KIND=JPRB),ALLOCATABLE :: ZGP3(:,:,:)
REAL(KIND=JPRB),POINTER :: ZFIELD1(:),ZFIELD2(:,:)
REAL(KIND=JPRB),POINTER :: ZSPEC_1D(:),ZSPEC_2D(:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZSPEC_1D_VEC(:,:),ZSPEC_2D_VEC(:,:,:)
CHARACTER(LEN=64) :: CLFNAME
LOGICAL :: LLMCC04, LLWRITE_SPEC
TYPE(FIELD_CONTAINER_SP) :: YLSPEC
TYPE(TYPE_ITERATOR) :: YLIT
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE FIELDS_WRITE
!==========================================================================================

SUBROUTINE FIELDS_READ(SELF,CDFNAME,KFIDS,LDREAD_SPEC)
USE FIELD_DEFINITIONS     , ONLY : FID, MAIN_FIELD_METADATA
USE FIELD_CONTAINER_SP_MOD, ONLY : FIELD_CONTAINER_SP,TYPE_ITERATOR
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
CHARACTER(LEN=*), OPTIONAL, INTENT(IN)  :: CDFNAME
INTEGER(KIND=JPIM),OPTIONAL,TARGET,INTENT(IN) :: KFIDS(:)
LOGICAL,OPTIONAL,INTENT(IN) :: LDREAD_SPEC

INTEGER(KIND=JPIM),POINTER :: IFIDS(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IFIDS_GP(:),IFIDS_SPEC(:),IFIDS_GP_REMOVE(:)
INTEGER(KIND=JPIM) :: JFLD,IFIELDS_GP,JF,IST,IEND,ID,IKGLO,JBLK
INTEGER(KIND=JPIM) :: IOPROC,ILOCGRB
INTEGER(KIND=JPIM) :: ILEVS(SELF%GEOM%YRDIMV%NFLEVG),IBSETS(SELF%GEOM%YRDIMV%NFLEVG)
INTEGER(KIND=JPIM) :: JL,IGRIBS(SELF%GEOM%YRDIMV%NFLEVG)
REAL(KIND=JPRB),ALLOCATABLE :: ZGP3(:,:,:)
REAL(KIND=JPRB),POINTER :: ZFIELD1(:),ZFIELD2(:,:)
REAL(KIND=JPRB),POINTER :: ZSPEC_1D(:),ZSPEC_2D(:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZSPEC_1D_VEC(:,:),ZSPEC_2D_VEC(:,:,:)
CHARACTER(LEN=64) :: CLFNAME
LOGICAL :: LLMCC04, LLREAD_SPEC
TYPE(FIELD_CONTAINER_SP) :: YLSPEC
TYPE(TYPE_ITERATOR) :: YLIT
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE








END SUBROUTINE FIELDS_READ
!==========================================================================================

SUBROUTINE FIELDS_RANDOM(SELF)
CLASS(FIELDS_BASE),       INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM) :: JBLK
TYPE(FIELD_ACCESS)  :: YLFAC
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE





END SUBROUTINE FIELDS_RANDOM
!=============================================================================

FUNCTION INTREST(KSOURCE,KREMOVE)

INTEGER(KIND=JPIM),INTENT(IN) :: KSOURCE(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KREMOVE(:)

INTEGER(KIND=JPIM),ALLOCATABLE :: INTREST(:)
INTEGER(KIND=JPIM) :: ITEMP(SIZE(KSOURCE)),INUM,J
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE







END FUNCTION INTREST

!==========================================================================================

SUBROUTINE SPLIT_SPEC_GP(KFIDS,KFIDS_SPEC,KFIDS_GP)
INTEGER(KIND=JPIM),INTENT(IN)  :: KFIDS(:)
INTEGER(KIND=JPIM),ALLOCATABLE,INTENT(OUT) :: KFIDS_SPEC(:)
INTEGER(KIND=JPIM),ALLOCATABLE,INTENT(OUT) :: KFIDS_GP(:)
INTEGER(KIND=JPIM),PARAMETER :: JPMAXLEN=500
INTEGER(KIND=JPIM) :: ISPECREP(4),ISPECTMP(JPMAXLEN),IGPTMP(JPMAXLEN),INSPEC,INGP,J












END SUBROUTINE SPLIT_SPEC_GP

!==========================================================================================

SUBROUTINE FIELDS_PGPSP(SELF,PGPSPGLO)
USE FIELD_DEFINITIONS, ONLY : FID
CLASS(FIELDS_BASE), INTENT(INOUT) :: SELF
REAL(KIND=JPRB),    INTENT(INOUT) :: PGPSPGLO(:,:)
INTEGER(KIND=JPIM) :: JBLK, JLOC, IKGLO, IST, IEND, ILOC, IOFFSET
INTEGER(KIND=JPIM), ALLOCATABLE :: IFIELDSPID(:)
REAL(KIND=JPRB), ALLOCATABLE :: ZGPSP(:)
TYPE(FIELD_ACCESS) :: YLFAC
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE







END SUBROUTINE FIELDS_PGPSP
!==========================================================================================

SUBROUTINE FIELDS_BASE_FINAL(THIS)
  TYPE(FIELDS_BASE) :: THIS
  
  
  
  
END SUBROUTINE FIELDS_BASE_FINAL

!==========================================================================================

END MODULE FIELDS_BASE_MOD
