MODULE FIELD_FACTORY_MODULE


USE FIELD_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

INTERFACE FIELD_NEW
  MODULE PROCEDURE FIELD_2RM_NEW_OWNER
  MODULE PROCEDURE FIELD_2RM_NEW_WRAPPER
  MODULE PROCEDURE FIELD_3RM_NEW_OWNER
  MODULE PROCEDURE FIELD_3RM_NEW_WRAPPER
  MODULE PROCEDURE FIELD_4RM_NEW_OWNER
  MODULE PROCEDURE FIELD_4RM_NEW_WRAPPER
  MODULE PROCEDURE FIELD_5RM_NEW_OWNER
  MODULE PROCEDURE FIELD_5RM_NEW_WRAPPER
  MODULE PROCEDURE FIELD_2RB_NEW_OWNER
  MODULE PROCEDURE FIELD_2RB_NEW_WRAPPER
  MODULE PROCEDURE FIELD_3RB_NEW_OWNER
  MODULE PROCEDURE FIELD_3RB_NEW_WRAPPER
  MODULE PROCEDURE FIELD_4RB_NEW_OWNER
  MODULE PROCEDURE FIELD_4RB_NEW_WRAPPER
  MODULE PROCEDURE FIELD_5RB_NEW_OWNER
  MODULE PROCEDURE FIELD_5RB_NEW_WRAPPER
  MODULE PROCEDURE FIELD_2RD_NEW_OWNER
  MODULE PROCEDURE FIELD_2RD_NEW_WRAPPER
  MODULE PROCEDURE FIELD_3RD_NEW_OWNER
  MODULE PROCEDURE FIELD_3RD_NEW_WRAPPER
  MODULE PROCEDURE FIELD_4RD_NEW_OWNER
  MODULE PROCEDURE FIELD_4RD_NEW_WRAPPER
  MODULE PROCEDURE FIELD_5RD_NEW_OWNER
  MODULE PROCEDURE FIELD_5RD_NEW_WRAPPER
  MODULE PROCEDURE FIELD_2IM_NEW_OWNER
  MODULE PROCEDURE FIELD_2IM_NEW_WRAPPER
  MODULE PROCEDURE FIELD_3IM_NEW_OWNER
  MODULE PROCEDURE FIELD_3IM_NEW_WRAPPER
  MODULE PROCEDURE FIELD_4IM_NEW_OWNER
  MODULE PROCEDURE FIELD_4IM_NEW_WRAPPER
  MODULE PROCEDURE FIELD_5IM_NEW_OWNER
  MODULE PROCEDURE FIELD_5IM_NEW_WRAPPER
  MODULE PROCEDURE FIELD_2LM_NEW_OWNER
  MODULE PROCEDURE FIELD_2LM_NEW_WRAPPER
  MODULE PROCEDURE FIELD_3LM_NEW_OWNER
  MODULE PROCEDURE FIELD_3LM_NEW_WRAPPER
  MODULE PROCEDURE FIELD_4LM_NEW_OWNER
  MODULE PROCEDURE FIELD_4LM_NEW_WRAPPER
  MODULE PROCEDURE FIELD_5LM_NEW_OWNER
  MODULE PROCEDURE FIELD_5LM_NEW_WRAPPER
END INTERFACE

PUBLIC :: FIELD_NEW

INTERFACE FIELD_DELETE
  MODULE PROCEDURE FIELD_2RM_DELETE
  MODULE PROCEDURE FIELD_3RM_DELETE
  MODULE PROCEDURE FIELD_4RM_DELETE
  MODULE PROCEDURE FIELD_5RM_DELETE
  MODULE PROCEDURE FIELD_2RB_DELETE
  MODULE PROCEDURE FIELD_3RB_DELETE
  MODULE PROCEDURE FIELD_4RB_DELETE
  MODULE PROCEDURE FIELD_5RB_DELETE
  MODULE PROCEDURE FIELD_2RD_DELETE
  MODULE PROCEDURE FIELD_3RD_DELETE
  MODULE PROCEDURE FIELD_4RD_DELETE
  MODULE PROCEDURE FIELD_5RD_DELETE
  MODULE PROCEDURE FIELD_2IM_DELETE
  MODULE PROCEDURE FIELD_3IM_DELETE
  MODULE PROCEDURE FIELD_4IM_DELETE
  MODULE PROCEDURE FIELD_5IM_DELETE
  MODULE PROCEDURE FIELD_2LM_DELETE
  MODULE PROCEDURE FIELD_3LM_DELETE
  MODULE PROCEDURE FIELD_4LM_DELETE
  MODULE PROCEDURE FIELD_5LM_DELETE
END INTERFACE FIELD_DELETE

PUBLIC :: FIELD_DELETE

CONTAINS

SUBROUTINE FIELD_2RM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_2RM), POINTER :: FIELD_PTR
TYPE(FIELD_2RM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (2)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (2)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_2RM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_2RM), POINTER :: FIELD_PTR
REAL(KIND=JPRM), TARGET, INTENT (IN) :: DATA (:,:)
TYPE(FIELD_2RM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (2)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_2RM_DELETE (FIELD_PTR)

CLASS(FIELD_2RM), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_3RM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_3RM), POINTER :: FIELD_PTR
TYPE(FIELD_3RM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (3)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_3RM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_3RM), POINTER :: FIELD_PTR
REAL(KIND=JPRM), TARGET, INTENT (IN) :: DATA (:,:,:)
TYPE(FIELD_3RM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_3RM_DELETE (FIELD_PTR)

CLASS(FIELD_3RM), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_4RM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_4RM), POINTER :: FIELD_PTR
TYPE(FIELD_4RM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_4RM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_4RM), POINTER :: FIELD_PTR
REAL(KIND=JPRM), TARGET, INTENT (IN) :: DATA (:,:,:,:)
TYPE(FIELD_4RM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_4RM_DELETE (FIELD_PTR)

CLASS(FIELD_4RM), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_5RM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_5RM), POINTER :: FIELD_PTR
TYPE(FIELD_5RM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (5)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_5RM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_5RM), POINTER :: FIELD_PTR
REAL(KIND=JPRM), TARGET, INTENT (IN) :: DATA (:,:,:,:,:)
TYPE(FIELD_5RM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_5RM_DELETE (FIELD_PTR)

CLASS(FIELD_5RM), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_2RB_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_2RB), POINTER :: FIELD_PTR
TYPE(FIELD_2RB_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (2)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (2)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_2RB_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_2RB), POINTER :: FIELD_PTR
REAL(KIND=JPRB), TARGET, INTENT (IN) :: DATA (:,:)
TYPE(FIELD_2RB_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (2)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_2RB_DELETE (FIELD_PTR)

CLASS(FIELD_2RB), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_3RB_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_3RB), POINTER :: FIELD_PTR
TYPE(FIELD_3RB_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (3)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_3RB_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_3RB), POINTER :: FIELD_PTR
REAL(KIND=JPRB), TARGET, INTENT (IN) :: DATA (:,:,:)
TYPE(FIELD_3RB_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_3RB_DELETE (FIELD_PTR)

CLASS(FIELD_3RB), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_4RB_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_4RB), POINTER :: FIELD_PTR
TYPE(FIELD_4RB_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_4RB_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_4RB), POINTER :: FIELD_PTR
REAL(KIND=JPRB), TARGET, INTENT (IN) :: DATA (:,:,:,:)
TYPE(FIELD_4RB_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_4RB_DELETE (FIELD_PTR)

CLASS(FIELD_4RB), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_5RB_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_5RB), POINTER :: FIELD_PTR
TYPE(FIELD_5RB_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (5)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_5RB_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_5RB), POINTER :: FIELD_PTR
REAL(KIND=JPRB), TARGET, INTENT (IN) :: DATA (:,:,:,:,:)
TYPE(FIELD_5RB_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_5RB_DELETE (FIELD_PTR)

CLASS(FIELD_5RB), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_2RD_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_2RD), POINTER :: FIELD_PTR
TYPE(FIELD_2RD_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (2)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (2)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_2RD_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_2RD), POINTER :: FIELD_PTR
REAL(KIND=JPRD), TARGET, INTENT (IN) :: DATA (:,:)
TYPE(FIELD_2RD_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (2)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_2RD_DELETE (FIELD_PTR)

CLASS(FIELD_2RD), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_3RD_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_3RD), POINTER :: FIELD_PTR
TYPE(FIELD_3RD_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (3)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_3RD_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_3RD), POINTER :: FIELD_PTR
REAL(KIND=JPRD), TARGET, INTENT (IN) :: DATA (:,:,:)
TYPE(FIELD_3RD_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_3RD_DELETE (FIELD_PTR)

CLASS(FIELD_3RD), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_4RD_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_4RD), POINTER :: FIELD_PTR
TYPE(FIELD_4RD_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_4RD_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_4RD), POINTER :: FIELD_PTR
REAL(KIND=JPRD), TARGET, INTENT (IN) :: DATA (:,:,:,:)
TYPE(FIELD_4RD_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_4RD_DELETE (FIELD_PTR)

CLASS(FIELD_4RD), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_5RD_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_5RD), POINTER :: FIELD_PTR
TYPE(FIELD_5RD_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (5)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_5RD_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_5RD), POINTER :: FIELD_PTR
REAL(KIND=JPRD), TARGET, INTENT (IN) :: DATA (:,:,:,:,:)
TYPE(FIELD_5RD_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_5RD_DELETE (FIELD_PTR)

CLASS(FIELD_5RD), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_2IM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_2IM), POINTER :: FIELD_PTR
TYPE(FIELD_2IM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (2)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (2)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_2IM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_2IM), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), TARGET, INTENT (IN) :: DATA (:,:)
TYPE(FIELD_2IM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (2)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_2IM_DELETE (FIELD_PTR)

CLASS(FIELD_2IM), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_3IM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_3IM), POINTER :: FIELD_PTR
TYPE(FIELD_3IM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (3)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_3IM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_3IM), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), TARGET, INTENT (IN) :: DATA (:,:,:)
TYPE(FIELD_3IM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_3IM_DELETE (FIELD_PTR)

CLASS(FIELD_3IM), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_4IM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_4IM), POINTER :: FIELD_PTR
TYPE(FIELD_4IM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_4IM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_4IM), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), TARGET, INTENT (IN) :: DATA (:,:,:,:)
TYPE(FIELD_4IM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_4IM_DELETE (FIELD_PTR)

CLASS(FIELD_4IM), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_5IM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_5IM), POINTER :: FIELD_PTR
TYPE(FIELD_5IM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (5)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_5IM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_5IM), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), TARGET, INTENT (IN) :: DATA (:,:,:,:,:)
TYPE(FIELD_5IM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_5IM_DELETE (FIELD_PTR)

CLASS(FIELD_5IM), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_2LM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_2LM), POINTER :: FIELD_PTR
TYPE(FIELD_2LM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (2)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (2)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_2LM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_2LM), POINTER :: FIELD_PTR
LOGICAL(KIND=JPLM), TARGET, INTENT (IN) :: DATA (:,:)
TYPE(FIELD_2LM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (2)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_2LM_DELETE (FIELD_PTR)

CLASS(FIELD_2LM), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_3LM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_3LM), POINTER :: FIELD_PTR
TYPE(FIELD_3LM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (3)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_3LM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_3LM), POINTER :: FIELD_PTR
LOGICAL(KIND=JPLM), TARGET, INTENT (IN) :: DATA (:,:,:)
TYPE(FIELD_3LM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_3LM_DELETE (FIELD_PTR)

CLASS(FIELD_3LM), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_4LM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_4LM), POINTER :: FIELD_PTR
TYPE(FIELD_4LM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_4LM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_4LM), POINTER :: FIELD_PTR
LOGICAL(KIND=JPLM), TARGET, INTENT (IN) :: DATA (:,:,:,:)
TYPE(FIELD_4LM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_4LM_DELETE (FIELD_PTR)

CLASS(FIELD_4LM), POINTER :: FIELD_PTR





END SUBROUTINE 

SUBROUTINE FIELD_5LM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED) 

CLASS(FIELD_5LM), POINTER :: FIELD_PTR
TYPE(FIELD_5LM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (5)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED







END SUBROUTINE 

SUBROUTINE FIELD_5LM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA) 

CLASS(FIELD_5LM), POINTER :: FIELD_PTR
LOGICAL(KIND=JPLM), TARGET, INTENT (IN) :: DATA (:,:,:,:,:)
TYPE(FIELD_5LM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT







END SUBROUTINE 

SUBROUTINE FIELD_5LM_DELETE (FIELD_PTR)

CLASS(FIELD_5LM), POINTER :: FIELD_PTR





END SUBROUTINE 


END MODULE
