MODULE MODEL_DIAGNOSTICS_MOD
  USE YOMCDDH , ONLY : TCDDH
  USE YOMLDDH , ONLY : TLDDH
  USE YOMMDDH , ONLY : TMDDH
  USE YOMSDDH , ONLY : TSDDH
  USE YOMTDDH , ONLY : TTDDH
  USE YOMGPDDH, ONLY : TGPDDH
  USE YOMPADDH, ONLY : TPADDH
  USE YOMSPDDH, ONLY : TSPDDH
  IMPLICIT NONE

  TYPE MODEL_DIAGNOSTICS_TYPE

!!  TYPE(GRIDPOINT_BUFFER)   :: GFUBUF, XFUBUF, GPPCBUF
  TYPE(TCDDH)              :: YRCDDH
  TYPE(TLDDH)              :: YRLDDH
  TYPE(TMDDH)              :: YRMDDH
  TYPE(TSDDH)              :: YRSDDH
  TYPE(TTDDH)              :: YRTDDH
  TYPE(TGPDDH)             :: YRGPDDH
  TYPE(TPADDH)             :: YRPADDH
  TYPE(TSPDDH)             :: YRSPDDH

CONTAINS
  
  PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 
    
  END TYPE MODEL_DIAGNOSTICS_TYPE

  !---------------------------------------------------------------------

  CONTAINS 

  SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
  
  CLASS(MODEL_DIAGNOSTICS_TYPE), INTENT(IN) :: SELF
  INTEGER                      , INTENT(IN) :: KDEPTH
  INTEGER                      , INTENT(IN) :: KOUTNO

  

  END SUBROUTINE PRINT_CONFIGURATION

END MODULE MODEL_DIAGNOSTICS_MOD
