MODULE MODEL_ATMOS_OCEAN_COUPLING_MOD
  USE YOMMCC, ONLY : TMCC
  USE YOMCOM, ONLY : TCOM
  USE YOMCOU, ONLY : TCOU
  IMPLICIT NONE

  TYPE MODEL_ATMOS_OCEAN_COUPLING_TYPE

    TYPE(TMCC)  :: YRMCC
    TYPE(TCOM)  :: YRCOM
    TYPE(TCOU)  :: YRCOU

    CONTAINS

    PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 
    
  END TYPE MODEL_ATMOS_OCEAN_COUPLING_TYPE

  !---------------------------------------------------------------------

  CONTAINS 

  SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
  
  CLASS(MODEL_ATMOS_OCEAN_COUPLING_TYPE), INTENT(IN) :: SELF
  INTEGER                               , INTENT(IN) :: KDEPTH
  INTEGER                               , INTENT(IN) :: KOUTNO

  
  
  
  
  
  END SUBROUTINE PRINT_CONFIGURATION

END MODULE MODEL_ATMOS_OCEAN_COUPLING_MOD
