INTERFACE
SUBROUTINE PPWETPOINT(YDCST, YDPHY,KIDIA,KFDIA,KLON,PAPRS,PT,PQV,PQL,PQI,PWETPOINT)

IMPORT

TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TPHY) ,INTENT(IN) :: YDPHY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLON
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQV(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQI(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWETPOINT(KLON)
END SUBROUTINE PPWETPOINT
END INTERFACE
