
MODULE SURFACE_VIEWS_PROGNOSTIC_MODULE
  ! The SURFACE_VIEWS type contains namespaced access to groups of
  ! array pointers according to individual surface variable groups.
  !
  !
  ! Variable naming conventions
  ! ---------------------------
  ! The top-level type `SURFACE_VIEWS_TYPE` holds multiple group
  ! types, each prefixed with `GSP_` for prognostic and `GSD_` for
  ! diagnostic variable groups.
  !
  ! Each group type holds a list of array views (pointers to
  ! sub-sections of the gobal array), each prefixed with `P` to
  ! indicate a thread-local view pointer. Data views of prognostic
  ! variables have an additional suffix that indicates the time index
  ! (eg.  `_T0`, `_T1` or `_T9`). The backend storage for each of
  ! these view pointers is provided by `FIELD_2D/FIELD_3D` objects, a
  ! reference to which is also stored on the group types and prefixed
  ! with `F_`.

USE PARKIND1, ONLY: JPIM, JPRB
USE FIELD_MODULE
! Using global imports here, since fypp notation breaks cmake's dependency analysis
USE SURFACE_VARIABLES_MOD
USE YOMDYN, ONLY : TDYN

IMPLICIT NONE

TYPE SURFACE_VIEW_GROUP_SOILB
  REAL(KIND=JPRB), POINTER :: PT_T0(:,:)   ! temperature
  REAL(KIND=JPRB), POINTER :: PT_T1(:,:)   ! temperature
  REAL(KIND=JPRB), POINTER :: PT_T9(:,:)   ! temperature
  REAL(KIND=JPRB), POINTER :: PQ_T0(:,:)   ! liquid water content
  REAL(KIND=JPRB), POINTER :: PQ_T1(:,:)   ! liquid water content
  REAL(KIND=JPRB), POINTER :: PQ_T9(:,:)   ! liquid water content
  REAL(KIND=JPRB), POINTER :: PTL_T0(:,:)   ! ice water content (for MF)
  REAL(KIND=JPRB), POINTER :: PTL_T1(:,:)   ! ice water content (for MF)
  REAL(KIND=JPRB), POINTER :: PTL_T9(:,:)   ! ice water content (for MF)
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_SOILB), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_3RB), POINTER :: F_T_T0=>NULL(), F_T_T1=>NULL(), F_T_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_Q_T0=>NULL(), F_Q_T1=>NULL(), F_Q_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_TL_T0=>NULL(), F_TL_T1=>NULL(), F_TL_T9=>NULL()
  CLASS (FIELD_4RB), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_SOILB_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_SOILB_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_SOILB_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_SOILB_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_SOILB_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_SOILB_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_SOILB_PHTFILT
  PROCEDURE :: FINAL => SURFACE_VIEW_GROUP_SOILB_FINAL
END TYPE SURFACE_VIEW_GROUP_SOILB

TYPE SURFACE_VIEW_GROUP_SNOWG
  REAL(KIND=JPRB), POINTER :: PF_T0(:,:)   ! content of surface snow
  REAL(KIND=JPRB), POINTER :: PF_T1(:,:)   ! content of surface snow
  REAL(KIND=JPRB), POINTER :: PF_T9(:,:)   ! content of surface snow
  REAL(KIND=JPRB), POINTER :: PA_T0(:,:)   ! snow albedo
  REAL(KIND=JPRB), POINTER :: PA_T1(:,:)   ! snow albedo
  REAL(KIND=JPRB), POINTER :: PA_T9(:,:)   ! snow albedo
  REAL(KIND=JPRB), POINTER :: PR_T0(:,:)   ! snow density
  REAL(KIND=JPRB), POINTER :: PR_T1(:,:)   ! snow density
  REAL(KIND=JPRB), POINTER :: PR_T9(:,:)   ! snow density
  REAL(KIND=JPRB), POINTER :: PT_T0(:,:)   ! total albedo (diagnostic for MF for LVGSN)
  REAL(KIND=JPRB), POINTER :: PT_T1(:,:)   ! total albedo (diagnostic for MF for LVGSN)
  REAL(KIND=JPRB), POINTER :: PT_T9(:,:)   ! total albedo (diagnostic for MF for LVGSN)
  REAL(KIND=JPRB), POINTER :: PW_T0(:,:)   ! Liquid water content
  REAL(KIND=JPRB), POINTER :: PW_T1(:,:)   ! Liquid water content
  REAL(KIND=JPRB), POINTER :: PW_T9(:,:)   ! Liquid water content
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_SNOWG), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_3RB), POINTER :: F_F_T0=>NULL(), F_F_T1=>NULL(), F_F_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_A_T0=>NULL(), F_A_T1=>NULL(), F_A_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_R_T0=>NULL(), F_R_T1=>NULL(), F_R_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_T_T0=>NULL(), F_T_T1=>NULL(), F_T_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_W_T0=>NULL(), F_W_T1=>NULL(), F_W_T9=>NULL()
  CLASS (FIELD_4RB), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_SNOWG_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_SNOWG_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_SNOWG_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_SNOWG_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_SNOWG_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_SNOWG_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_SNOWG_PHTFILT
  PROCEDURE :: FINAL => SURFACE_VIEW_GROUP_SNOWG_FINAL
END TYPE SURFACE_VIEW_GROUP_SNOWG

TYPE SURFACE_VIEW_GROUP_LAKEB
  REAL(KIND=JPRB), POINTER :: PLICT_T0(:)   ! lake ice temperature
  REAL(KIND=JPRB), POINTER :: PLICT_T1(:)   ! lake ice temperature
  REAL(KIND=JPRB), POINTER :: PLICT_T9(:)   ! lake ice temperature
  REAL(KIND=JPRB), POINTER :: PLMLT_T0(:)   ! lake mixed-layer temperature
  REAL(KIND=JPRB), POINTER :: PLMLT_T1(:)   ! lake mixed-layer temperature
  REAL(KIND=JPRB), POINTER :: PLMLT_T9(:)   ! lake mixed-layer temperature
  REAL(KIND=JPRB), POINTER :: PLTLT_T0(:)   ! lake total layer temperature
  REAL(KIND=JPRB), POINTER :: PLTLT_T1(:)   ! lake total layer temperature
  REAL(KIND=JPRB), POINTER :: PLTLT_T9(:)   ! lake total layer temperature
  REAL(KIND=JPRB), POINTER :: PLBLT_T0(:)   ! lake bottom layer temperature
  REAL(KIND=JPRB), POINTER :: PLBLT_T1(:)   ! lake bottom layer temperature
  REAL(KIND=JPRB), POINTER :: PLBLT_T9(:)   ! lake bottom layer temperature
  REAL(KIND=JPRB), POINTER :: PLSHF_T0(:)   ! lake shape factor
  REAL(KIND=JPRB), POINTER :: PLSHF_T1(:)   ! lake shape factor
  REAL(KIND=JPRB), POINTER :: PLSHF_T9(:)   ! lake shape factor
  REAL(KIND=JPRB), POINTER :: PLICD_T0(:)   ! lake ice depth
  REAL(KIND=JPRB), POINTER :: PLICD_T1(:)   ! lake ice depth
  REAL(KIND=JPRB), POINTER :: PLICD_T9(:)   ! lake ice depth
  REAL(KIND=JPRB), POINTER :: PLMLD_T0(:)   ! lake mixed-layer depth
  REAL(KIND=JPRB), POINTER :: PLMLD_T1(:)   ! lake mixed-layer depth
  REAL(KIND=JPRB), POINTER :: PLMLD_T9(:)   ! lake mixed-layer depth
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_LAKEB), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_LICT_T0=>NULL(), F_LICT_T1=>NULL(), F_LICT_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LMLT_T0=>NULL(), F_LMLT_T1=>NULL(), F_LMLT_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LTLT_T0=>NULL(), F_LTLT_T1=>NULL(), F_LTLT_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LBLT_T0=>NULL(), F_LBLT_T1=>NULL(), F_LBLT_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LSHF_T0=>NULL(), F_LSHF_T1=>NULL(), F_LSHF_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LICD_T0=>NULL(), F_LICD_T1=>NULL(), F_LICD_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LMLD_T0=>NULL(), F_LMLD_T1=>NULL(), F_LMLD_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_LAKEB_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_LAKEB_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_LAKEB_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_LAKEB_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_LAKEB_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_LAKEB_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_LAKEB_PHTFILT
  PROCEDURE :: FINAL => SURFACE_VIEW_GROUP_LAKEB_FINAL
END TYPE SURFACE_VIEW_GROUP_LAKEB

TYPE SURFACE_VIEW_GROUP_RESVR
  REAL(KIND=JPRB), POINTER :: PT_T0(:)   ! skin temperature (Ts)
  REAL(KIND=JPRB), POINTER :: PT_T1(:)   ! skin temperature (Ts)
  REAL(KIND=JPRB), POINTER :: PT_T9(:)   ! skin temperature (Ts)
  REAL(KIND=JPRB), POINTER :: PW_T0(:)   ! skin water content (Wskin) at ECMWF superficial reservoir water content (Ws) at MF
  REAL(KIND=JPRB), POINTER :: PW_T1(:)   ! skin water content (Wskin) at ECMWF superficial reservoir water content (Ws) at MF
  REAL(KIND=JPRB), POINTER :: PW_T9(:)   ! skin water content (Wskin) at ECMWF superficial reservoir water content (Ws) at MF
  REAL(KIND=JPRB), POINTER :: PFC_T0(:)   ! skin water content (Wl) at MF
  REAL(KIND=JPRB), POINTER :: PFC_T1(:)   ! skin water content (Wl) at MF
  REAL(KIND=JPRB), POINTER :: PFC_T9(:)   ! skin water content (Wl) at MF
  REAL(KIND=JPRB), POINTER :: PIC_T0(:)   ! superficial reservoir ice
  REAL(KIND=JPRB), POINTER :: PIC_T1(:)   ! superficial reservoir ice
  REAL(KIND=JPRB), POINTER :: PIC_T9(:)   ! superficial reservoir ice
  REAL(KIND=JPRB), POINTER :: PFP1_T0(:)   ! interpolated Ts for 2nd part of 927-FULLPOS
  REAL(KIND=JPRB), POINTER :: PFP1_T1(:)   ! interpolated Ts for 2nd part of 927-FULLPOS
  REAL(KIND=JPRB), POINTER :: PFP1_T9(:)   ! interpolated Ts for 2nd part of 927-FULLPOS
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_RESVR), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_T_T0=>NULL(), F_T_T1=>NULL(), F_T_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_W_T0=>NULL(), F_W_T1=>NULL(), F_W_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_FC_T0=>NULL(), F_FC_T1=>NULL(), F_FC_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_IC_T0=>NULL(), F_IC_T1=>NULL(), F_IC_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_FP1_T0=>NULL(), F_FP1_T1=>NULL(), F_FP1_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_RESVR_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_RESVR_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_RESVR_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_RESVR_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_RESVR_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_RESVR_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_RESVR_PHTFILT
  PROCEDURE :: FINAL => SURFACE_VIEW_GROUP_RESVR_FINAL
END TYPE SURFACE_VIEW_GROUP_RESVR

TYPE SURFACE_VIEW_GROUP_CLS
  REAL(KIND=JPRB), POINTER :: PTCLS_T0(:)   ! 2m temperature
  REAL(KIND=JPRB), POINTER :: PTCLS_T1(:)   ! 2m temperature
  REAL(KIND=JPRB), POINTER :: PTCLS_T9(:)   ! 2m temperature
  REAL(KIND=JPRB), POINTER :: PHUCLS_T0(:)   ! 2m humidity
  REAL(KIND=JPRB), POINTER :: PHUCLS_T1(:)   ! 2m humidity
  REAL(KIND=JPRB), POINTER :: PHUCLS_T9(:)   ! 2m humidity
  REAL(KIND=JPRB), POINTER :: PUCLS_T0(:)   ! 10m U-wind
  REAL(KIND=JPRB), POINTER :: PUCLS_T1(:)   ! 10m U-wind
  REAL(KIND=JPRB), POINTER :: PUCLS_T9(:)   ! 10m U-wind
  REAL(KIND=JPRB), POINTER :: PVCLS_T0(:)   ! 10m V-wind
  REAL(KIND=JPRB), POINTER :: PVCLS_T1(:)   ! 10m V-wind
  REAL(KIND=JPRB), POINTER :: PVCLS_T9(:)   ! 10m V-wind
  REAL(KIND=JPRB), POINTER :: PNUCLS_T0(:)   ! 10m neutral U-wind
  REAL(KIND=JPRB), POINTER :: PNUCLS_T1(:)   ! 10m neutral U-wind
  REAL(KIND=JPRB), POINTER :: PNUCLS_T9(:)   ! 10m neutral U-wind
  REAL(KIND=JPRB), POINTER :: PNVCLS_T0(:)   ! 10m neutral V-wind
  REAL(KIND=JPRB), POINTER :: PNVCLS_T1(:)   ! 10m neutral V-wind
  REAL(KIND=JPRB), POINTER :: PNVCLS_T9(:)   ! 10m neutral V-wind
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_CLS), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_TCLS_T0=>NULL(), F_TCLS_T1=>NULL(), F_TCLS_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_HUCLS_T0=>NULL(), F_HUCLS_T1=>NULL(), F_HUCLS_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_UCLS_T0=>NULL(), F_UCLS_T1=>NULL(), F_UCLS_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_VCLS_T0=>NULL(), F_VCLS_T1=>NULL(), F_VCLS_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_NUCLS_T0=>NULL(), F_NUCLS_T1=>NULL(), F_NUCLS_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_NVCLS_T0=>NULL(), F_NVCLS_T1=>NULL(), F_NVCLS_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_CLS_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_CLS_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_CLS_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_CLS_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_CLS_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_CLS_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_CLS_PHTFILT
  PROCEDURE :: FINAL => SURFACE_VIEW_GROUP_CLS_FINAL
END TYPE SURFACE_VIEW_GROUP_CLS

TYPE SURFACE_VIEW_GROUP_OML
  REAL(KIND=JPRB), POINTER :: PTO_T0(:,:)   ! temperature
  REAL(KIND=JPRB), POINTER :: PTO_T1(:,:)   ! temperature
  REAL(KIND=JPRB), POINTER :: PTO_T9(:,:)   ! temperature
  REAL(KIND=JPRB), POINTER :: PSO_T0(:,:)   ! salinity
  REAL(KIND=JPRB), POINTER :: PSO_T1(:,:)   ! salinity
  REAL(KIND=JPRB), POINTER :: PSO_T9(:,:)   ! salinity
  REAL(KIND=JPRB), POINTER :: PUO_T0(:,:)   ! U velocity
  REAL(KIND=JPRB), POINTER :: PUO_T1(:,:)   ! U velocity
  REAL(KIND=JPRB), POINTER :: PUO_T9(:,:)   ! U velocity
  REAL(KIND=JPRB), POINTER :: PVO_T0(:,:)   ! V velocity
  REAL(KIND=JPRB), POINTER :: PVO_T1(:,:)   ! V velocity
  REAL(KIND=JPRB), POINTER :: PVO_T9(:,:)   ! V velocity
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_OML), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_3RB), POINTER :: F_TO_T0=>NULL(), F_TO_T1=>NULL(), F_TO_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_SO_T0=>NULL(), F_SO_T1=>NULL(), F_SO_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_UO_T0=>NULL(), F_UO_T1=>NULL(), F_UO_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_VO_T0=>NULL(), F_VO_T1=>NULL(), F_VO_T9=>NULL()
  CLASS (FIELD_4RB), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_OML_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_OML_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_OML_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_OML_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_OML_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_OML_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_OML_PHTFILT
  PROCEDURE :: FINAL => SURFACE_VIEW_GROUP_OML_FINAL
END TYPE SURFACE_VIEW_GROUP_OML

TYPE SURFACE_VIEW_GROUP_EXTRP
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_EXTRP), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_4RB), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_EXTRP_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_EXTRP_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_EXTRP_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_EXTRP_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_EXTRP_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_EXTRP_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_EXTRP_PHTFILT
  PROCEDURE :: FINAL => SURFACE_VIEW_GROUP_EXTRP_FINAL
END TYPE SURFACE_VIEW_GROUP_EXTRP

TYPE SURFACE_VIEW_GROUP_XTRP2
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_XTRP2), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_XTRP2_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_XTRP2_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_XTRP2_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_XTRP2_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_XTRP2_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_XTRP2_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_XTRP2_PHTFILT
  PROCEDURE :: FINAL => SURFACE_VIEW_GROUP_XTRP2_FINAL
END TYPE SURFACE_VIEW_GROUP_XTRP2

TYPE SURFACE_VIEW_GROUP_CANRI
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_CANRI), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_CANRI_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_CANRI_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_CANRI_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_CANRI_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_CANRI_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_CANRI_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_CANRI_PHTFILT
  PROCEDURE :: FINAL => SURFACE_VIEW_GROUP_CANRI_FINAL
END TYPE SURFACE_VIEW_GROUP_CANRI


CONTAINS

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_INIT(SELF, VARIABLE_GROUP)
    
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_SOILB), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    
    
    
    
    
    
    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_UPDATE_VIEW(SELF, BLOCK_INDEX)
    
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    
    
    
    
    
    
    
    
    
    

    
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_INIT(SELF, VARIABLE_GROUP)
    
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_SNOWG), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_UPDATE_VIEW(SELF, BLOCK_INDEX)
    
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_INIT(SELF, VARIABLE_GROUP)
    
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_LAKEB), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_UPDATE_VIEW(SELF, BLOCK_INDEX)
    
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_INIT(SELF, VARIABLE_GROUP)
    
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_RESVR), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_UPDATE_VIEW(SELF, BLOCK_INDEX)
    
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_INIT(SELF, VARIABLE_GROUP)
    
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_CLS), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_UPDATE_VIEW(SELF, BLOCK_INDEX)
    
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_OML_INIT(SELF, VARIABLE_GROUP)
    
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_OML), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_OML_UPDATE_VIEW(SELF, BLOCK_INDEX)
    
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    
    
    
    
    
    
    
    
    
    
    
    
    

    
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_INIT(SELF, VARIABLE_GROUP)
    
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_EXTRP), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_UPDATE_VIEW(SELF, BLOCK_INDEX)
    
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    

    
  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_INIT(SELF, VARIABLE_GROUP)
    
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_XTRP2), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_UPDATE_VIEW(SELF, BLOCK_INDEX)
    
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    

    
  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_INIT(SELF, VARIABLE_GROUP)
    
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_CANRI), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_UPDATE_VIEW(SELF, BLOCK_INDEX)
    
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    

    
  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_UPDATE_VIEW



  ! Timestepping utility subroutines for prognostics variables
  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET9TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF

    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET1TO9(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF

    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET1TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF

    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET0TO1(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF

    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    
    

    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_FINAL(SELF)
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_FINAL

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET9TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF

    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET1TO9(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF

    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET1TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF

    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET0TO1(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF

    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    
    

    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_FINAL(SELF)
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_FINAL

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET9TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF

    
    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET1TO9(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF

    
    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET1TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF

    
    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET0TO1(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF

    
    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    
    

    
    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_FINAL(SELF)
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_FINAL

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET9TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF

    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET1TO9(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF

    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET1TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF

    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET0TO1(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF

    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    
    

    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_FINAL(SELF)
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_FINAL

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET9TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF

    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET1TO9(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF

    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET1TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF

    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET0TO1(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF

    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    
    

    
    
    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_FINAL(SELF)
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_FINAL

  SUBROUTINE SURFACE_VIEW_GROUP_OML_SET9TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF

    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_OML_SET1TO9(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF

    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_OML_SET1TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF

    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_OML_SET0TO1(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF

    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_OML_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    
    

    
    
    
    
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_OML_FINAL(SELF)
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_OML_FINAL

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET9TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET1TO9(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET1TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET0TO1(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    
    

  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_FINAL(SELF)
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_FINAL

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET9TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET1TO9(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET1TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET0TO1(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    
    

  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_FINAL(SELF)
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_FINAL

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET9TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET1TO9(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET1TO0(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET0TO1(SELF)
    
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    
    

  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_FINAL(SELF)
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_FINAL


END MODULE SURFACE_VIEWS_PROGNOSTIC_MODULE
