MODULE YOENEUR

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

TYPE :: TENEUR
INTEGER(KIND=JPIM) :: NCOU, NBR, NBNEURMAX
INTEGER(KIND=JPIM) :: KLEV_NN

INTEGER(KIND=JPIM), ALLOCATABLE :: NBNEUR(:,:)
REAL(KIND=JPRB),    ALLOCATABLE :: WNELN(:,:,:,:)
REAL(KIND=JPRB),    ALLOCATABLE :: ENTREEMOY(:,:), RAPIN(:,:)
REAL(KIND=JPRB),    ALLOCATABLE :: SORTIEMOY(:,:), RAPOUT(:,:)
REAL(KIND=JPRB),    ALLOCATABLE :: PDFSDX(:,:,:,:)
REAL(KIND=JPRB),    ALLOCATABLE :: AAM_NN(:), BBM_NN(:)
!----------------------------------------------------------------------------
CONTAINS
  PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 
END TYPE TENEUR
!============================================================================

!!TYPE(TENEUR), POINTER :: YRENEUR => NULL()


CONTAINS

SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)

CLASS(TENEUR), INTENT(IN) :: SELF
INTEGER      , INTENT(IN) :: KDEPTH
INTEGER      , INTENT(IN) :: KOUTNO

INTEGER :: IDEPTHLOC


















END SUBROUTINE PRINT_CONFIGURATION

END MODULE YOENEUR
