MODULE YOMSRFTLAD

USE PARKIND1  ,ONLY : JPRB,JPIM

IMPLICIT NONE

SAVE

! ------ SKIN TEMPERATURE FOR LINEARIZED PHYSICS

! GPSURF  : BUFFER FOR PERTURBATION OF TOP LAYER SURF. FIELDS 
!           (SKIN TEMPERATURE,...)
! NGSKIN  : NUMBER OF TOP SOIL FIELDS FOR PERTURBATION

! LREGSF  : .TRUE. if the regularization for SURF computation is used

TYPE :: TSRFTLAD
REAL(KIND=JPRB),ALLOCATABLE :: GPTSKIN0(:,:,:)
REAL(KIND=JPRB),ALLOCATABLE :: GPTSKIN9(:,:,:)

INTEGER(KIND=JPIM) :: NGSKIN

LOGICAL :: LREGSF
!----------------------------------------------------------------------------
CONTAINS
  PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 
END TYPE TSRFTLAD
!============================================================================

!!TYPE(TSRFTLAD), POINTER :: YRSRFTLAD => NULL()

!     ------------------------------------------------------------------

CONTAINS

SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
  
  CLASS(TSRFTLAD), INTENT(IN) :: SELF
  INTEGER        , INTENT(IN) :: KDEPTH
  INTEGER        , INTENT(IN) :: KOUTNO

  INTEGER :: IDEPTHLOC

  
  
  
  
  
  
  
 
END SUBROUTINE PRINT_CONFIGURATION

END MODULE YOMSRFTLAD
